var m=void 0,
	s=!0,
	t=null,
	v=!1;
function fa(e){
	return function(h){
		this[e]=h
	}
}
var ga,B;
function ua(e,h){
	var j,g,d,c,a,b,f,k,I,x=h&&h.split("/"),w=E.map,y=w&&w["*"]||{};
	if(e&&"."===e.charAt(0)&&h){
		x=x.slice(0,x.length-1);
		e=x.concat(e.split("/"));
		for(k=0;k<e.length;k+=1)
			if(j=e[k],"."===j)e.splice(k,1),
				k-=1;
			else if(".."===j)
				if(1===k&&(".."===e[2]||".."===e[0]))
					break;
				else 0<k&&(e.splice(k-1,2),k-=2);
				e=e.join("/")
	}if((x||y)&&w){
				j=e.split("/");
				for(k=j.length;0<k;k-=1){
					g=j.slice(0,k).join("/");
					if(x)
						for(I=x.length;0<I;I-=1)
							if(d=w[x.slice(0,I).join("/")])
								if(d=d[g]){
									c=d;
									a=k;
									break
								}if(c)
								break;
!b&&(y&&y[g])&&(b=y[g],f=k)}
!c&&b&&(c=b,a=f);
c&&(j.splice(0,a,c),
	e=j.join("/"))
}return e
}
function va(e,h){
	return function(){
		return wa.apply(m,xa.call(arguments,0).concat([e,h]))
	}
}
function La(e){
	return function(h){
		V[e]=h
	}
}
function Ma(e){
	if(gb.hasOwnProperty(e)){
		var h=gb[e];
		delete gb[e];
		hb[e]=s;
		ib.apply(m,h)
	}if(!V.hasOwnProperty(e)&&!hb.hasOwnProperty(e))
	throw Error("No "+e);return V[e]
}
function xb(e){
	var h,j=e?e.indexOf("!"):-1;
	-1<j&&(h=e.substring(0,j),e=e.substring(j+1,e.length));return[h,e]}
var ib,wa,yb,W,V={},gb={},E={},hb={},xa=[].slice;yb=function(e,h){var j,g=xb(e),d=g[0],e=g[1];d&&(d=ua(d,h),j=Ma(d));d?e=j&&j.normalize?j.normalize(e,function(c){return ua(c,h)}):ua(e,h):(e=ua(e,h),g=xb(e),d=g[0],e=g[1],d&&(j=Ma(d)));return{Kd:d?d+"!"+e:e,uf:e,gg:d,ee:j}};W={xf:function(e){return va(e)},b:function(e){var h=V[e];return"undefined"!==typeof h?h:V[e]={}},sf:function(e){return{id:e,uri:"",b:V[e],Fc:function(){return E&&E.Fc&&E.Fc[e]||{}}}}};
ib=function(e,h,j,g){var d,c,a,b,f=[],k,g=g||e;if("function"===typeof j){h=!h.length&&j.length?["require","exports","module"]:h;for(b=0;b<h.length;b+=1)if(a=yb(h[b],g),c=a.Kd,"require"===c)f[b]=W.xf(e);else if("exports"===c)f[b]=W.b(e),k=s;else if("module"===c)d=f[b]=W.sf(e);else if(V.hasOwnProperty(c)||gb.hasOwnProperty(c)||hb.hasOwnProperty(c))f[b]=Ma(c);else if(a.ee)a.ee.load(a.uf,va(g,s),La(c),{}),f[b]=V[c];else throw Error(e+" missing "+c);h=j.apply(V[e],f);if(e)if(d&&d.b!==m&&d.b!==V[e])V[e]=
d.b;else if(h!==m||!k)V[e]=h}else e&&(V[e]=j)};ga=wa=function(e,h,j,g,d){if("string"===typeof e)return W[e]?W[e](h):Ma(yb(e,h).Kd);e.splice||(E=e,h.splice?(e=h,h=j,j=t):e=m);h=h||function(){};"function"===typeof j&&(j=g,g=d);g?ib(m,e,h,j):setTimeout(function(){ib(m,e,h,j)},15);return wa};wa.Fc=function(e){E=e;return wa};B=function(e,h,j){h.splice||(j=h,h=[]);gb[e]=[e,h,j]};B.Sf={$f:s};B("lib/almond",function(){});
B("f19",["require","exports","module"],function(e,h,j){var g={precision:1E-6,L:[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1],multiply:function c(a,b){var f=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1];f[0]=a[0]*b[0]+a[1]*b[4]+a[2]*b[8]+a[3]*b[12];f[1]=a[0]*b[1]+a[1]*b[5]+a[2]*b[9]+a[3]*b[13];f[2]=a[0]*b[2]+a[1]*b[6]+a[2]*b[10]+a[3]*b[14];f[3]=a[0]*b[3]+a[1]*b[7]+a[2]*b[11]+a[3]*b[15];f[4]=a[4]*b[0]+a[5]*b[4]+a[6]*b[8]+a[7]*b[12];f[5]=a[4]*b[1]+a[5]*b[5]+a[6]*b[9]+a[7]*b[13];f[6]=a[4]*b[2]+a[5]*b[6]+a[6]*b[10]+
a[7]*b[14];f[7]=a[4]*b[3]+a[5]*b[7]+a[6]*b[11]+a[7]*b[15];f[8]=a[8]*b[0]+a[9]*b[4]+a[10]*b[8]+a[11]*b[12];f[9]=a[8]*b[1]+a[9]*b[5]+a[10]*b[9]+a[11]*b[13];f[10]=a[8]*b[2]+a[9]*b[6]+a[10]*b[10]+a[11]*b[14];f[11]=a[8]*b[3]+a[9]*b[7]+a[10]*b[11]+a[11]*b[15];f[12]=a[12]*b[0]+a[13]*b[4]+a[14]*b[8]+a[15]*b[12];f[13]=a[12]*b[1]+a[13]*b[5]+a[14]*b[9]+a[15]*b[13];f[14]=a[12]*b[2]+a[13]*b[6]+a[14]*b[10]+a[15]*b[14];f[15]=a[12]*b[3]+a[13]*b[7]+a[14]*b[11]+a[15]*b[15];return 2>=arguments.length?f:c.apply(t,[f].concat(Array.prototype.slice.call(arguments,
2)))},q:function a(b,f){var k=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1];k[0]=b[0]*f[0]+b[1]*f[4]+b[2]*f[8];k[1]=b[0]*f[1]+b[1]*f[5]+b[2]*f[9];k[2]=b[0]*f[2]+b[1]*f[6]+b[2]*f[10];k[4]=b[4]*f[0]+b[5]*f[4]+b[6]*f[8];k[5]=b[4]*f[1]+b[5]*f[5]+b[6]*f[9];k[6]=b[4]*f[2]+b[5]*f[6]+b[6]*f[10];k[8]=b[8]*f[0]+b[9]*f[4]+b[10]*f[8];k[9]=b[8]*f[1]+b[9]*f[5]+b[10]*f[9];k[10]=b[8]*f[2]+b[9]*f[6]+b[10]*f[10];k[12]=b[12]*f[0]+b[13]*f[4]+b[14]*f[8]+f[12];k[13]=b[12]*f[1]+b[13]*f[5]+b[14]*f[9]+f[13];k[14]=b[12]*f[2]+b[13]*f[6]+
b[14]*f[10]+f[14];return 2>=arguments.length?k:a.apply(t,[k].concat(Array.prototype.slice.call(arguments,2)))},Ea:function(a,b){return[a[0],a[1],a[2],0,a[4],a[5],a[6],0,a[8],a[9],a[10],0,a[12]+b[0],a[13]+b[1],a[14]+b[2],1]},c:function(a,b,f){return[1,0,0,0,0,1,0,0,0,0,1,0,a,b,f,1]},Y:function(a,b,f){return[a,0,0,0,0,b,0,0,0,0,f,0,0,0,0,1]},pe:function(a){var b=Math.cos(a),a=Math.sin(a);return[1,0,0,0,0,b,a,0,0,-a,b,0,0,0,0,1]},Xa:function(a){var b=Math.cos(a),a=Math.sin(a);return[b,0,-a,0,0,1,0,0,
a,0,b,0,0,0,0,1]},yf:function(a){var b=Math.cos(a),a=Math.sin(a);return[b,a,0,0,-a,b,0,0,0,0,1,0,0,0,0,1]},rotate:function(a,b,f){var k=Math.cos(a),a=Math.sin(a),e=Math.cos(b),b=Math.sin(b),g=Math.cos(f),f=Math.sin(f),j=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1];j[0]=e*g;j[1]=k*f+a*b*g;j[2]=a*f-k*b*g;j[4]=-e*f;j[5]=k*g-a*b*f;j[6]=a*g+k*b*f;j[8]=b;j[9]=-a*e;j[10]=k*e;return j},Nc:function(a){for(var a=a.slice(0),b=0;b<a.length;b++)Math.abs(a[b])<g.precision&&(a[b]=0);return"matrix3d("+a.join()+")"},Ha:function(a,
b,f){return[1,0,0,0,Math.tan(f),1,0,0,Math.tan(b),Math.tan(a),1,0,0,0,0,1]},Da:function(a){return[a[12],a[13],a[14]]},Rc:function(a){var b=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1],f=a[5]*a[10]-a[6]*a[9],k=a[4]*a[10]-a[6]*a[8],e=a[4]*a[9]-a[5]*a[8],g=a[1]*a[10]-a[2]*a[9],j=a[0]*a[10]-a[2]*a[8],h=a[0]*a[9]-a[1]*a[8],q=a[1]*a[6]-a[2]*a[5],l=a[0]*a[6]-a[2]*a[4],C=a[0]*a[5]-a[1]*a[4],z=1/(a[0]*f-a[1]*k+a[2]*e);b[0]=z*f;b[1]=-z*g;b[2]=z*q;b[4]=-z*k;b[5]=z*j;b[6]=-z*l;b[8]=z*e;b[9]=-z*h;b[10]=z*C;b[12]=-a[12]*
b[0]-a[13]*b[4]-a[14]*b[8];b[13]=-a[12]*b[1]-a[13]*b[5]-a[14]*b[9];b[14]=-a[12]*b[2]-a[13]*b[6]-a[14]*b[10];return b},ja:function(a){function b(a,b,f){f||(f=0);return Math.sqrt(a*a+b*b+f*f)}var f=b(a[0],a[1],a[2]);0<a[0]&&a[0]!=f&&(f*=-1);var k=a[0]+f,e=2/(k*k+a[1]*a[1]+a[2]*a[2]),f=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1];f[0]=1-e*k*k;f[1]=-e*k*a[1];f[2]=-e*k*a[2];f[5]=1-e*a[1]*a[1];f[6]=-e*a[1]*a[2];f[10]=1-e*a[2]*a[2];f[4]=f[1];f[8]=f[2];f[9]=f[6];k=g.q(a,f);e=b(k[5],k[6]);0<k[5]&&k[5]!=e&&(e*=-1);var e=
k[5]+e,j=2/(e*e+k[6]*k[6]),h=[1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1];h[5]=1-j*e*e;h[6]=-j*e*k[6];h[9]=h[6];h[10]=1-j*k[6]*k[6];f=g.q(f,h);k=g.q(a,f);e=g.Y(0>k[0]?-1:1,0>k[5]?-1:1,0>k[10]?-1:1);k=g.q(e,k);f=g.q(f,e);e={};e.translate=g.Da(a);e.rotate=[Math.atan2(-f[6],f[10]),Math.asin(f[2]),Math.atan2(-f[1],f[0])];e.rotate[0]||(e.rotate[0]=0,e.rotate[2]=Math.atan2(f[4],f[5]));e.scale=[k[0],k[5],k[10]];e.Ha=[Math.atan(k[9]/e.scale[2]),Math.atan(k[8]/e.scale[2]),Math.atan(k[4]/e.scale[0])];return e},We:function(a){var b=
g.Y(a.scale[0],a.scale[1],a.scale[2]),f=g.Ha(a.Ha[0],a.Ha[1],a.Ha[2]),k=g.rotate(a.rotate[0],a.rotate[1],a.rotate[2]);return g.Ea(g.q(b,f,k),a.translate)},Hd:function(a,b){if(!a||!b)return v;if(a==b)return s;for(var f=0;f<a.length;f++)if(Math.abs(a[f]-b[f])>=g.precision)return v;return s},Xc:function(a){a=a.slice(0);if(a[0]==Math.PI/2||a[0]==-Math.PI/2)a[0]=-a[0],a[1]=Math.PI-a[1],a[2]-=Math.PI;a[0]>Math.PI/2&&(a[0]-=Math.PI,a[1]=Math.PI-a[1],a[2]-=Math.PI);a[0]<-Math.PI/2&&(a[0]+=Math.PI,a[1]=-Math.PI-
a[1],a[2]-=Math.PI);for(;a[1]<-Math.PI;)a[1]+=2*Math.PI;for(;a[1]>=Math.PI;)a[1]-=2*Math.PI;for(;a[2]<-Math.PI;)a[2]+=2*Math.PI;for(;a[2]>=Math.PI;)a[2]-=2*Math.PI;return a}};j.b=g});
B("f32",["require","exports","module","f19"],function(e,h,j){function g(c,a){this.Aa=c;this.M={};this.Wb={};this.Zb={};this.Vc={};this.Xb={};this.Yb={};this.Ua={};this.j={};this.hd={};this.$e={Aa:this.Aa,kb:[],Wc:0};this.a=a;this.a||(this.a={});this.a.ye||(this.a.ye="surface");this.a.Pd||(this.a.Pd="group");this.a.ae||(this.a.ae=30);this.a.Qb||(this.a.Qb=0);this.a.ha||(this.a.ha="c");this.a.size||(this.a.size=[c.offsetWidth,c.offsetHeight])}var d=e("f19");g.prototype=
{Bc:function(c){var a={},b={},f={},k={},e={},g={},j={};if(c)if("undefined"!=typeof c.id)this.hd[c.id]=c,b[c.id]=d.L,a[c.id]=1;else if("number"==typeof c.length)for(var h=0;h<c.length;h++){groupPrefix=h.toString()+"A";var q=this.Bc(c[h]),l;for(l in q.$b)a[l]=q.$b[l];for(l in q.u)b[l]=q.u[l];for(l in q.Nb)f[l]=q.Nb[l];for(l in q.j)k[l]=groupPrefix+q.j[l];for(l in q.Rb)e[groupPrefix+l]=q.Rb[l];for(l in q.Pb)g[groupPrefix+l]=q.Pb[l];for(l in q.Ob)j[groupPrefix+l]=q.Ob[l]}else if(c.target){var C=c.target;
l="object"==typeof c.transform?c.transform:d.L;var z="number"==typeof c.opacity?c.opacity:1,X=c.group,c=c.ha;X&&(e.X=l,g.X=z);var F=this.Bc(C),C=F.u,R=F.$b,Y=F.Nb,Z=F.j,A=F.Rb,ha=F.Pb,F=F.Ob;for(h in C)C.hasOwnProperty(h)&&(b[h]=X||Z.hasOwnProperty(h)?C[h]:d.q(C[h],l),a[h]=X||Z.hasOwnProperty(h)?R[h]:z*R[h],f[h]=Y[h]||c,Z.hasOwnProperty(h)?k[h]=Z[h]:X&&(k[h]="X"));for(q in A)A.hasOwnProperty(q)&&(e[q]=d.q(A[q],l));for(q in ha)ha.hasOwnProperty(q)&&(g[q]=z*ha[q]);for(q in F)F.hasOwnProperty(q)&&(j[q]=
F[q])}return{u:b,j:k,Rb:e,$b:a,Pb:g,Nb:f,Ob:j}},Ke:function(c){var a={},b=[],f;for(f in c)if(c.hasOwnProperty(f)){var d=this.Ua[f];d&&(a.hasOwnProperty(d)?b.push(d):a[d]=c[f])}for(f=0;f<b.length;f++)a.hasOwnProperty(b[f])&&delete a[b[f]];return a},Ne:function(c){for(var a in this.Ua)this.Ua.hasOwnProperty(a)&&(this.Ua[a]=c[this.Ua[a]]);var b={};for(a in this.j)if(this.j.hasOwnProperty(a))if(c.hasOwnProperty(a)){b.hasOwnProperty(c[a])||(b[c[a]]=[]);for(var f=0;f<this.j[a].length;f++)this.j[a][f].nb=
c[a],b[c[a]].push(this.j[a][f])}else for(f=0;f<this.j[a].length;f++)delete this.j[a][f].nb;this.j=b},nd:function(c,a){a=a||this.a.ha;if("tl"==a)return c;var b=0;if("r"==a||"tr"==a||"br"==a)b=this.a.size[0];else if(!a||"t"==a||"c"==a||"b"==a)b=0.5*this.a.size[0];var f=0;if("bl"==a||"b"==a||"br"==a)f=this.a.size[1];else if(!a||"l"==a||"c"==a||"r"==a)f=0.5*this.a.size[1];return d.Ea(c,[b,f,0])},He:function(c,a,b){b=b||this.a.ha;if("tl"==b)return a;var f=0;if("r"==b||"tr"==b||"br"==b)f=-c[0];else if(!b||
"t"==b||"c"==b||"b"==b)f=-0.5*c[0];var k=0;if("bl"==b||"b"==b||"br"==b)k=-c[1];else if(!b||"l"==b||"c"==b||"r"==b)k=-0.5*c[1];return d.Ea(a,[f,k,0])},update:function(c){var a=this.Bc(c),c=a.u,b=a.j,f=a.$b,k=a.Nb,e=a.Rb,g=a.Pb,a=a.Ob,j=this.Ke(b);this.Ne(j);for(var h in this.M)!c.hasOwnProperty(h)&&this.Zb[h]&&(this.detach(h),this.Zb[h]=v);for(h in c)c.hasOwnProperty(h)&&this.Lf(h,c[h],b[h],f[h],k[h],b.hasOwnProperty(h)?d.q(c[h],e[b[h]]):c[h]);for(h in e)e.hasOwnProperty(h)&&this.Kf(h,e[h],g[h],a[h])},
Kf:function(c,a,b,f){if(c=this.j[c])for(var k=0;k<c.length;k++){if(!d.Hd(c[k].$d,a)){c[k].$d=a;var e=d.q(d.c(0,0,this.a.Qb),this.nd(a,f));c[k].Aa.style.webkitTransform=d.Nc(e)}c[k].opacity!=b&&(c[k].opacity=b,c[k].Aa.style.opacity=b)}},Te:function(c,a){this.j[c]||(this.j[c]=[]);var b=this.j[c];a.nb=c;b.push(a)},wf:function(c){this.j.hasOwnProperty(c)||(this.j[c]=[]);for(var a=this.j[c],b=0,f=this.a.ae;b<a.length&&!(0<a[b].kb.length||a[b].Wc<f);)b++;b>=a.length&&(f=document.createElement("div"),f.classList.add(this.a.Pd),
this.Aa.appendChild(f),a.push({nb:c,Aa:f,Wc:0,kb:[]}));return a[b]},Lf:function(c,a,b,f,k,e){var g=this.hd[c];e||(e=a);var h=this.Vc[c];h&&b&&(h.nb||this.Te(b,h),h.nb!=b&&this.detach(c));this.Ua[c]=b;if((e=g.Sc(e))||this.Zb[c]){this.M[c]||this.Se(c,b);h=this.M[c];if(g.fa||this.Wb[c])g.fd(h),this.Wb[c]=v;a=this.He(g.hf(),a,k);d.Hd(a,this.Xb[c])||(this.Xb[c]=a,h.style.webkitTransform=b?d.Nc(d.Ea(a,[0,0,-this.a.Qb])):d.Nc(this.nd(a,k)));f!=this.Yb[c]&&(this.Yb[c]=f,h.style.opacity=0.999999<f?0.999999:
f);this.Zb[c]=e}else this.M[c]&&this.detach(c)},Se:function(c,a){var b=a!=m?this.wf(a):this.$e,f;b.kb.length?f=b.kb.pop():(b.Wc++,f=document.createElement("div"),f.classList.add(this.a.ye),b.Aa.appendChild(f));this.Vc[c]=b;this.M[c]=f;this.Wb[c]=s;return f},detach:function(c){var a=this.M[c];delete this.M[c];delete this.Xb[c];delete this.Yb[c];a&&(this.hd[c].Dc(a),this.Vc[c].kb.push(a),a.style.webkitTransform="scale3d(0, 0, 0)");this.Wb[c]=s},jc:function(c){this.a.ha=c},vb:function(c){this.a.size=
c.slice(0);this.Xb={};this.Yb={};for(var a in this.j)for(var c=this.j[a],b=0;b<c.length;b++)delete c[b].$d,delete c[b].opacity}};j.b=g});
B("f24",["require","exports","module"],function(e,h,j){function g(d){this.vf=d;this.next=m}g.prototype={get:function(){return this.vf},g:function(d){d=new g(d);this.Cf(d);return d},Cf:fa("next"),execute:function(){var d=this.next,c=this.get();if(d){if(d.length){var a=[];for(b in d)a.push(d[b].execute());return c.t(a)}return c.t(d.execute())}if("function"==typeof c)return c();if(c.t)return c.t();var d=[],b;for(b in c)d.push(c[b].t());return d}};j.b=g});
B("f11",["require","exports","module"],function(e,h,j){function g(d){this.Qc=[];d&&(this.Qc=d.slice(0));this.Tb={}}g.prototype={d:function(d,c){c||(c={});c.origin=this;for(var a=0;a<this.Qc.length;a++)this.Qc[a].d(d,c);var b=this.Tb[d];if(b)for(a=0;a<b.length;a++)b[a].call(this,c)},Va:function(d,c){this.Tb[d]||(this.Tb[d]=[]);this.Tb[d].push(c);return this}};j.b=g});
B("f6",["require","exports","module","f24","f11"],function(e,h,j){function g(a){this.pa=a;this.mc=m;this.Id=new c}var d=e("f24"),c=e("f11");g.prototype={Gc:function(a){return this.mc=new d(a)},update:function(){this.mc&&this.pa.update(this.mc.execute())},d:function(a,b){this.Id.d(a,b)},Va:function(a,b){this.Id.Va(a,b)}};j.b=g});
B("f8",["require","exports","module"],function(e,h,j){function g(d){this.controllers=[];d&&(this.controllers=d.slice(0))}g.prototype={ya:function(d){0>this.controllers.indexOf(d)&&this.controllers.push(d)},ic:function(d){d=this.controllers.indexOf(d);0<=d&&this.controllers.splice(d,1)},N:function(d){this.controllers=d.slice(0)},d:function(d,c){c||(c={});c.origin||(c.origin=this);for(var a=0;a<this.controllers.length;a++)this.controllers[a].d(d,c)}};j.b=g});
B("f10","require exports module f32 f6 f8".split(" "),function(e,h,j){function g(){window.scrollTo(0,0);d(function(){for(var a=window.innerWidth,f=window.innerHeight,c=0;c<b.length;c++){b[c].d("resize");var d=b[c].pa;d&&d.vb([a,f])}})}function d(a){k.push(a)}var c=e("f32"),a=e("f6"),e=e("f8"),b=[],f=[],k=[],I=(new Date).getTime(),x=m;requestAnimationFrame(function q(){var a=(new Date).getTime();
x=1E3/(a-I);I=a;for(a=0;a<f.length;a++){var c=f[a];"function"==typeof c?c.call(this):c.update()}for(a=0;a<k.length;a++)k[a].call(this);k=[];for(a=0;a<b.length;a++)b[a].update();requestAnimationFrame(q)});window.addEventListener("resize",g);g();window.addEventListener("touchmove",function(a){a.preventDefault()});for(var w=new e,e="touchstart touchmove touchend touchcancel click keydown keyup keypress mouseenter mousemove mouseleave".split(" "),h=0;h<e.length;h++)(function(a){document.body.addEventListener(a,
function(b){w.d(a,b)})}).call(this,e[h]);j.b={Db:function(a){0>f.indexOf(a)&&f.push(a)},hg:function(a){a=f.indexOf(a);0<=a&&f.splice(a,1)},ig:function(a){f=a.slice(0)},ya:function(a){w.ya(a)},ic:function(a){w.ic(a)},N:function(a){w.N(a)},Cd:function(f){surfaceManager=f.pa?f.pa:new c(f,{Qb:-1E5});f.pa=surfaceManager;f=new a(surfaceManager);b.push(f);return f},Yf:function(){return x},be:d}});
B("f4",["require","exports","module","f24"],function(e,h,j){function g(){this.reset()}var d=e("f24");g.prototype={n:function(c){c=new d(c);this.M.push(c);return c},reset:function(){this.M=[]},t:function(){for(var c=[],a=0;a<this.M.length;a++)c.push(this.M[a].execute());return c}};j.b=g});
B("f35",["require","exports","module"],function(e,h,j){function g(d){this.ea=t;this.Cb=[];this.Cc=[];this.Yd=0;this.$a({duration:500,m:g.r.of});this.set(d)}g.r={of:function(d){return d},Hc:function(d){return d*d},Ba:function(d){return d*(2-d)},mb:function(d){return 0.5>=d?2*d*d:-2*d*d+4*d-1},Vf:function(d){return d*(2.25-1.25*d)},lc:function(d){return(1-d)*Math.sin(6*Math.PI*d)+d}};g.prototype={wd:function(d){0>=this.Cb.length?this.set(this.state):(d||(d=this.getTime()),this.ea=
this.Cb.shift(),this.startTime=d,this.xe=this.qd(this.state))},Re:function(d){if(this.ea&&(d||(d=this.getTime()),this.Yd!=d)){this.Yd=d;var c=this.xe,a=this.ea[0],b=this.ea[2],d=(d-this.startTime)/this.ea[1],f=Math.min(Math.max(d,0),1);if("object"==typeof this.state)for(var k in this.state)this.state.hasOwnProperty(k)&&(this.state[k]=this.ud(c[k],a[k],b(f)));else this.state=this.ud(c,a,b(f));1<=d&&(c=this.Cc.shift(),this.wd(),c&&c())}},ud:function(d,c,a){return(1-a)*d+a*c},qd:function(d){if("object"==
typeof d){if(d.slice)return d.slice(0);var c={},a;for(a in d)d.hasOwnProperty(a)&&(c[a]=d[a]);return c}return d},Me:function(d){var c=this.rd,a={m:c.m};c.duration&&(a.duration=c.duration);c.speed&&(a.speed=c.speed);if("boolean"==typeof d)return a;"number"==typeof d.duration&&(a.duration=d.duration);d.m&&(a.m=d.m);d.speed&&(a.speed=d.speed);return a},$a:function(d){this.rd={};for(var c in d)d.hasOwnProperty(c)&&(this.rd[c]=d[c])},set:function(d,c,a){if(c){c=this.Me(c);if(c.speed){var b=this.get(),
f=0;if("object"==typeof b)for(var k in b)b.hasOwnProperty(k)&&(f+=Math.pow(d[k]-b[k],2));else f=Math.pow(d-b,2);c.duration=Math.sqrt(f)/c.speed}this.Cb.push([d,c.duration,c.m]);this.Cc.push(a);this.ea||this.wd()}else this.startTime=0,this.xe=this.state=this.qd(d),this.ea=t,this.Cb=[],this.Cc=[],a&&a()},getTime:function(){return this.pf?this.pf:(new Date).getTime()},get:function(d){this.Re(d);return this.state},Sb:function(){return!!this.ea},k:function(){this.set(this.get())}};j.b=g});
B("f12",["require","exports","module","f35"],function(e,h,j){function g(c,a){"undefined"==typeof c&&(c=0);"undefined"==typeof a&&(a=s);this.wa=new d(c);this.yb=a}var d=e("f35");g.prototype={show:function(c){this.set(1,this.yb,c)},ia:function(c){this.set(0,this.yb,c)},set:function(c,a,b){this.wa.k();this.wa.set(c,a,b)},t:function(c){var a=this.wa.get();return a?{opacity:a,target:c}:t},Sc:function(c){c||(c=0);return 1<=c?1==this.wa.get():this.wa.get()>
c}};j.b=g});
B("f34",["require","exports","module","f19","f35"],function(e,h,j){function g(a,b,f){a||(a=d.L);"number"!=typeof b&&(b=1);this.va=new c([0,0,0,0,0,0,0,0,0,1,1,1]);this.ac=new c(b);this.setTransform(a);this.tb(b);this.jc(f)}var d=e("f19"),c=e("f35");g.td=function(a){return[].concat(a.translate,a.rotate,a.Ha,a.scale)};g.Le=function(a){return{translate:[a[0],a[1],a[2]],rotate:[a[3],a[4],a[5]],Ha:[a[6],a[7],a[8]],scale:[a[9],a[10],
a[11]]}};g.prototype={F:function(){return this.va.Sb()?d.We(g.Le(this.va.get())):this.Mc},setTransform:function(a,b,f){b?(this.zd&&(this.va.set(g.td(d.ja(this.Mc))),this.zd=v),this.va.set(g.td(d.ja(a)),b,f)):(this.va.k(),this.zd=s);this.Mc=a},Pc:function(){return this.ac.get()},tb:function(a,b,f){this.ac.set(a,b,f)},jc:fa("ha"),Af:function(a){this.va.$a(a);this.ac.$a(a)},k:function(){this.va.k();this.ac.k()},Ta:function(){return this.va.Sb()},t:function(a){return{transform:this.F(),opacity:this.Pc(),
ha:this.ha,target:a}}};j.b=g});
B("f0",["require","exports","module","f19","f35"],function(e,h,j){function g(a){this.a=a;this.a||(this.a={});this.a.hasOwnProperty("xBounds")||(this.a.sc=[-Infinity,Infinity]);this.a.hasOwnProperty("yBounds")||(this.a.tc=[-Infinity,Infinity]);this.a.hasOwnProperty("zBounds")||(this.a.uc=[-Infinity,Infinity]);this.Wa=new c([0,0,0]);this.Ya=new c([0,0,0]);this.Ja=new c([0,0,0]);this.Wa.$a({duration:3E3,m:c.r.Ba});this.Ya.$a({duration:1E3,m:c.r.Ba});this.Ja.$a({duration:1E3,
m:c.r.Ba})}var d=e("f19"),c=e("f35");g.prototype={fb:function(){var a=this.Wa.get(),b=this.Ya.get(),f=this.Ja.get(),f=d.rotate(-f[0],-f[1],-f[2]),b=d.q(d.yf(b[2]),d.Xa(b[1]),d.pe(b[0])),c=d.c(-a[0],-a[1],-a[2]);return d.q(c,b,d.c(a[0],a[1],a[2]),f,c)},t:function(a){a||(a=[]);return{transform:this.fb(),target:a,group:s}},Ta:function(){return this.Wa.Sb()||this.Ja.Sb()},k:function(){this.Wa.k();this.Ya.k();this.Ja.k()},O:function(){return this.Wa.get()},z:function(a,b,
f){a[0]<this.a.sc[0]&&(a[0]=this.a.sc[0]);a[0]>this.a.sc[1]&&(a[0]=this.a.sc[1]);a[1]<this.a.tc[0]&&(a[1]=this.a.tc[0]);a[1]>this.a.tc[1]&&(a[1]=this.a.tc[1]);a[2]<this.a.uc[0]&&(a[2]=this.a.uc[0]);a[2]>this.a.uc[1]&&(a[2]=this.a.uc[1]);this.Wa.set(a,b,f)},ga:function(){return this.Ya.get()},A:function(a,b,f){if(b){for(var c=this.ga(),d=0;3>d;d++)a[d]>0.5*Math.PI&&c[d]<=-0.5*Math.PI&&(c[d]+=2*Math.PI),a[d]<-0.5*Math.PI&&c[d]>=0.5*Math.PI&&(c[d]-=2*Math.PI);this.Ya.set(c)}this.Ya.set(a,b,f)},Ra:function(){return this.Ja.get()},
D:function(a,b,c){if(b){for(var d=this.Ra(),e=0;3>e;e++)a[e]>0.5*Math.PI&&d[e]<=-0.5*Math.PI&&(d[e]+=2*Math.PI),a[e]<-0.5*Math.PI&&d[e]>=0.5*Math.PI&&(d[e]-=2*Math.PI);this.Ja.set(d)}this.Ja.set(a,b,c)},ce:function(){var a=this.Ra();if(a[0]||a[1]||a[2])a=d.ja(d.Rc(this.fb())),this.z(a.translate),this.A([-a.rotate[0],-a.rotate[1],-a.rotate[2]]),this.D([0,0,0])},Xc:function(){var a=this.ga();if(a[0]||a[1]||a[2])a=d.ja(this.fb()),this.z([-a.translate[0],-a.translate[1],-a.translate[2]]),this.D([-a.rotate[0],
-a.rotate[1],-a.rotate[2]]),this.A([0,0,0])},gf:function(){var a=this.Ra();if(!a[0]&&!a[1]&&!a[2])return this.ga();a=d.ja(d.Rc(this.fb()));return[-a.rotate[0],-a.rotate[1],-a.rotate[2]]},qf:function(a,b,c){var e=d.ja(d.Rc(a)),a=e.translate,e=d.Xc(e.rotate);this.A([0,0,0],b);this.D([-e[0],-e[1],-e[2]],b);this.z([-a[0],-a[1],-a[2]],b,c)}};j.b=g});
B("f2",["require","exports","module"],function(e,h,j){function g(d){this.e=d}g.prototype={move:function(d,c,a){var b=this.e.O();this.e.z([b[0]+d[0],b[1]+d[1],b[2]+d[2]],c,a)},rotate:function(d,c,a){var b=this.e.ga();this.e.A([b[0]+d[0],b[1]+d[1],b[2]+d[2]],c,a)},o:function(d,c,a){var b=this.e.Ra();this.e.D([b[0]+d[0],b[1]+d[1],b[2]+d[2]],c,a)}};j.b=g});
B("f1",["require","exports","module","f2"],function(e,h,j){function g(a,b){this.e=a;this.a=b;this.a||(this.a={});this.a.ie||(this.a.ie=0.8);this.a.Ae||(this.a.Ae=0.2);this.a.ne||(this.a.ne=0.0030);this.a.te||(this.a.te=0.0030);this.a.ke||(this.a.ke=700);this.a.Ce||(this.a.Ce=1E3);this.a.bd||(this.a.bd=50);this.a.gd||(this.a.gd=50);this.a.ze||(this.a.ze=100);this.a.je||(this.a.je=2E3);this.a.Be||(this.a.Be=2E3);this.a.P||(this.a.P=0.5);this.a.R||(this.a.R=0.5);
this.a.wb||(this.a.wb=Math.PI/12);this.a.$c||(this.a.$c=500);this.a.v||(this.a.v=d);this.l=new this.a.v(this.e,this.a);this.state=t}var d=e("f2");g.md={Ma:1,ca:2,ba:3};var c=g.md;g.prototype={sb:function(){return Math.max(this.e.O()[2]/300,1)},ec:function(a){this.e.k();this.la=a.targetTouches[0].pageX;this.ma=a.targetTouches[0].pageY;this.cb=this.bb=0;this.G=(new Date).getTime()},dc:function(a){var b=a.targetTouches[0].pageX,a=a.targetTouches[0].pageY,c=b-this.la,d=a-this.ma;this.e.gf();
var e=this.a.ie*this.sb(),c=-e*c,d=-e*d;Math.abs(c)>Math.abs(d)&&(d=0);Math.abs(d)>Math.abs(c)&&(c=0);this.l.move([c,d,0]);this.la=b;this.ma=a;b=(new Date).getTime();this.bb=c/(b-this.G);this.cb=d/(b-this.G);this.G=b},cc:function(){var a=this.a.ke,b=this.sb()*this.a.je,c=a*this.bb,a=a*this.cb;c>b&&(c=b);a>b&&(a=b);c<-b&&(c=-b);a<-b&&(a=-b);(c||a)&&this.l.move([c,a,0],s)},pc:function(a){this.e.k();this.Wd=this.Ee(a);this.re=0;this.G=(new Date).getTime()},oc:function(a){a=this.Ee(a);diffDistance=a-
this.Wd;var b=3*Math.min(Math.abs(diffDistance)/this.a.ze,1)+1;dZ=-this.sb()*b*this.a.Ae*diffDistance;this.l.move([0,0,dZ]);this.Wd=a;a=(new Date).getTime();b=a-this.G;if(1<b||0<b&&0!=dZ)this.re=dZ/b;this.G=a},nc:function(){var a=this.a.Ce*this.re,b=this.sb()*this.a.Be;a>b&&(a=b);a<-b&&(a=-b);a&&this.l.move([0,0,a],s)},dd:function(a){this.e.k();var b=a.changedTouches.length-1;this.xb=a.changedTouches[b].identifier;this.la=a.changedTouches[b].pageX;this.ma=a.changedTouches[b].pageY;this.oe=v},cd:function(a){for(var b,
c=0;c<a.changedTouches.length;c++)a.changedTouches[c].identifier==this.xb&&(b=a.changedTouches[c]);if(b){a=b.pageX;b=b.pageY;var d=this.a.ne,c=d*(a-this.la),d=-d*(b-this.ma);this.l.rotate([-d,-c,0]);this.oe=s;var e=(new Date).getTime();this.bb=c/(e-this.G);this.cb=d/(e-this.G);this.G=e;this.la=a;this.ma=b}},ad:function(a){for(var b,c=0;c<a.changedTouches.length;c++)a.changedTouches[c].identifier==this.xb&&(b=a.changedTouches[c]);if(b)if(this.oe){b=this.a.bd;a=b*this.bb;b*=this.cb;a>this.a.P&&(a=this.a.P);
b>this.a.P&&(b=this.a.P);a<-this.a.P&&(a=-this.a.P);b<-this.a.P&&(b=-this.a.P);var c=this.e.ga(),d=[c[0]-b,c[1]-a,c[2]];Math.abs(d[0])<this.a.wb&&(b=c[0]);Math.abs(d[1])<this.a.wb&&(a=c[1]);(a||b)&&this.l.rotate([-b,-a,0],s)}else this.Ga()},Ga:function(){this.e.A([0,0,0],{duration:this.a.$c})},we:function(a){this.e.k();var b=a.changedTouches.length-1;this.xb=a.changedTouches[b].identifier;this.la=a.changedTouches[b].pageX;this.ma=a.changedTouches[b].pageY;this.ve=v},ue:function(a){for(var b,c=0;c<
a.changedTouches.length;c++)a.changedTouches[c].identifier==this.xb&&(b=a.changedTouches[c]);if(b){a=b.pageX;b=b.pageY;var d=this.a.te,c=d*(a-this.la),d=-d*(b-this.ma);this.l.o([-d,-c,0]);this.ve=s;var e=(new Date).getTime();this.bb=c/(e-this.G);this.cb=d/(e-this.G);this.G=e;this.la=a;this.ma=b}},se:function(a){for(var b,c=0;c<a.changedTouches.length;c++)a.changedTouches[c].identifier==this.xb&&(b=a.changedTouches[c]);if(b)if(this.ve){b=this.a.gd;a=b*this.bb;b*=this.cb;a>this.a.R&&(a=this.a.R);b>
this.a.R&&(b=this.a.R);a<-this.a.R&&(a=-this.a.R);b<-this.a.R&&(b=-this.a.R);var c=this.e.Ra(),d=[c[0]-b,c[1]-a,c[2]];Math.abs(d[0])<this.a.wb&&(b=c[0]);Math.abs(d[1])<this.a.wb&&(a=c[1]);(a||b)&&this.l.o([-b,-a,0],s)}else this.Ka()},Ka:function(){this.e.D([0,0,0],{duration:this.a.$c})},Ee:function(a){var b=a.touches[0],c=a.touches[1],a=c.pageX-b.pageX,b=c.pageY-b.pageY;return Math.sqrt(a*a+b*b)},ua:function(a){!this.state&&1>=a.touches.length?(this.state=c.Ma,this.ec(a)):this.state!=c.ca&&2==a.touches.length?
(this.state=c.ca,this.pc(a)):this.state!=c.ba&&3==a.touches.length&&(this.state=c.ba,this.dd(a))},ta:function(a){this.state==c.Ma&&this.dc(a);this.state==c.ca&&this.oc(a);this.state==c.ba&&this.cd(a)},sa:function(a){this.state==c.Ma&&(this.cc(a),this.state=t);this.state==c.ca&&2>a.touches.length&&(this.nc(a),this.state=t);this.state==c.ba&&3>a.touches.length&&(this.ad(a),this.state=t)},d:function(a,b){"touchstart"==a?this.ua(b):"touchmove"==a?this.ta(b):"touchend"==a&&this.sa(b)}};g.prototype.trigger=
g.prototype.d;j.b=g});
B("f30",["require","exports","module","f1"],function(e,h,j){function g(){d.apply(this,arguments)}var d=e("f1");g.prototype={ua:function(a){!this.state&&1>=a.touches.length?(this.state="pan",this.ec(a)):"swim"!=this.state&&2==a.touches.length?(this.state="swim",this.pc(a)):"spin"!=this.state&&3==a.touches.length&&(this.state="spin",this.we(a))},ta:function(a){"pan"==this.state&&this.dc(a);"swim"==this.state&&this.oc(a);"spin"==this.state&&
this.ue(a)},sa:function(a){"pan"==this.state&&(this.cc(a),this.state=t);"swim"==this.state&&2>a.touches.length&&(this.nc(a),this.state=t);"spin"==this.state&&3>a.touches.length&&(this.se(a),this.state=t)},Ka:function(){d.prototype.Ka.call(this,arguments);d.prototype.Ga.call(this,arguments)}};for(var c in d.prototype)d.prototype.hasOwnProperty(c)&&!g.prototype.hasOwnProperty(c)&&(g.prototype[c]=d.prototype[c]);j.b=g});
B("f29",["require","exports","module","f1","f19"],function(e,h,j){function g(){d.apply(this,arguments);this.a.C||(this.a.C=0);this.a.Fb||(this.a.Fb=[0,0,0])}var d=e("f1"),c=e("f19");g.prototype={ua:function(a){if(!this.state&&1>=a.touches.length)this.state=1,this.ec(a);else if(2!=this.state&&2==a.touches.length)this.state=2,this.pc(a);else if(4!=this.state&&3!=this.state&&3==a.touches.length){var d=c.ja(this.e.fb()),
e=this.a.Fb[0]-d.translate[0],g=this.a.Fb[1]-d.translate[1],d=this.a.Fb[2]-d.translate[2];Math.sqrt(e*e+g*g+d*d)>this.a.C?(this.e.Xc(),this.state=4,this.we(a)):(this.e.ce(),this.state=3,this.dd(a))}},ta:function(a){1==this.state&&this.dc(a);2==this.state&&this.oc(a);3==this.state&&this.cd(a);4==this.state&&this.ue(a)},sa:function(a){1==this.state&&(this.cc(a),this.state=t);2==this.state&&2>a.touches.length&&(this.nc(a),this.state=t);3==this.state&&3>a.touches.length&&(this.ad(a),this.state=t);4==
this.state&&3>a.touches.length&&(this.se(a),this.state=t)},Ka:function(){d.prototype.Ga.call(this,arguments);d.prototype.Ka.call(this,arguments)},Ga:function(){d.prototype.Ga.call(this,arguments);d.prototype.Ka.call(this,arguments)}};for(var a in d.prototype)d.prototype.hasOwnProperty(a)&&!g.prototype.hasOwnProperty(a)&&(g.prototype[a]=d.prototype[a]);j.b=g});
B("f21",["require","exports","module","f1"],function(e,h,j){function g(){d.apply(this,arguments)}var d=e("f1"),c=d.md;g.prototype={sb:function(){return 2},ua:function(a){!this.state&&1>=a.touches.length?(this.state=c.Ma,this.ec(a)):this.state!=c.ca&&2==a.touches.length?(this.state=c.ca,this.pc(a)):this.state!=c.ba&&3==a.touches.length&&(this.state=c.ba,this.dd(a))},ta:function(a){this.state==c.Ma&&(this.e.ce(),this.dc(a));this.state==
c.ca&&this.oc(a);this.state==c.ba&&this.cd(a)},sa:function(a){this.state==c.Ma&&(this.cc(a),this.state=t);this.state==c.ca&&2>a.touches.length&&(this.nc(a),this.state=t);this.state==c.ba&&3>a.touches.length&&(this.ad(a),this.state=t)},Ga:function(){d.prototype.Ga.call(this,arguments);d.prototype.Ka.call(this,arguments)}};for(var a in d.prototype)d.prototype.hasOwnProperty(a)&&!g.prototype.hasOwnProperty(a)&&(g.prototype[a]=d.prototype[a]);j.b=g});
B("f18",["require","exports","module","f2"],function(e,h,j){function g(c,a){this.e=c;this.a=a;this.a||(this.a={});"undefined"==typeof this.a.Vb&&(this.a.Vb=1);"undefined"==typeof this.a.W&&(this.a.W=0.0010);"undefined"==typeof this.a.$&&(this.a.$=0.0010);this.a.Vd||(this.a.Vd=500);this.a.o||(this.a.o=v);this.a.ka||(this.a.ka=v);this.a.Sa||(this.a.Sa=v);this.a.v||(this.a.v=d);this.l=new this.a.v(c,a);if(!this.a.Wf){var b=this;setTimeout(function k(){b.update();
setTimeout(k,20)},20)}this.Xd=(new Date).getTime();this.timestamp=(new Date).getTime();this.xd()}var d=e("f2");g.prototype={xd:function(){this.H=[0,0,0];this.w=[0,0,0];this.B=[0,0,0]},update:function(){var c=(new Date).getTime(),a=c-this.timestamp;c-this.Xd>this.a.Vd&&this.xd();(this.H[0]||this.H[1]||this.H[2])&&this.l.move([this.H[0]*this.a.Vb*a,this.H[1]*this.a.Vb*a,this.H[2]*this.a.Vb*a]);(this.w[0]||this.w[1]||this.w[2])&&this.l.rotate([this.w[0]*this.a.W*a,this.w[1]*this.a.W*
a,this.w[2]*this.a.W*a]);(this.B[0]||this.B[1]||this.B[2])&&this.l.o([this.B[0]*this.a.$*a,this.B[1]*this.a.$*a,this.B[2]*this.a.$*a]);this.timestamp=c},d:function(c,a){function b(a,b){this.a.o?(38==a.keyCode?this.B[0]=-b:40==a.keyCode?this.B[0]=b:37==a.keyCode?this.B[1]=b:39==a.keyCode&&(this.B[1]=-b),this.a.ka&&(this.B[1]*=-1),this.a.Sa&&(this.B[0]*=-1)):(38==a.keyCode?this.w[0]=b:40==a.keyCode?this.w[0]=-b:37==a.keyCode?this.w[1]=-b:39==a.keyCode&&(this.w[1]=b),this.a.ka&&(this.w[1]*=-1),this.a.Sa&&
(this.w[0]*=-1));87==a.keyCode?a.shiftKey?this.H[1]=-b:this.H[2]=-b:65==a.keyCode?this.H[0]=-b:83==a.keyCode?a.shiftKey?this.H[1]=b:this.H[2]=b:68==a.keyCode&&(this.H[0]=b)}"keydown"==c?(this.Xd=(new Date).getTime(),b.call(this,a,1),this.update()):"keyup"==c&&b.call(this,a,0)}};g.prototype.trigger=g.prototype.d;j.b=g});
B("f20",["require","exports","module","f2"],function(e,h,j){function g(c,a){this.e=c;this.a=a;this.a||(this.a={});"undefined"==typeof this.a.W&&(this.a.W=0.0050);"undefined"==typeof this.a.$&&(this.a.$=0.0050);this.a.ka||(this.a.ka=v);this.a.Sa||(this.a.Sa=v);this.a.o||(this.a.o=v);this.a.v||(this.a.v=d);this.a.qb||(this.a.qb=100);this.l=new this.a.v(c,a)}var d=e("f2");g.prototype={d:function(c,a){if("mouseenter"==c)a.ctrlKey&&(this.Fa=m),this.Fa=
[a.screenX,a.screenY];else if("mousemove"==c)if(a.ctrlKey)this.Fa=m;else{var b=[a.screenX,a.screenY];if(this.Fa){var d=[this.Fa[1]-b[1],b[0]-this.Fa[0],0];if(d[0]||d[1]||d[2])d[0]=Math.min(Math.max(d[0],-this.a.qb),this.a.qb),d[1]=Math.min(Math.max(d[1],-this.a.qb),this.a.qb),this.a.ka&&(d[1]=-d[1]),this.a.Sa&&(d[0]=-d[0]),this.a.o?this.l.o([d[0]*-this.a.$,d[1]*-this.a.$,d[2]*-this.a.$]):this.l.rotate([d[0]*this.a.W,d[1]*this.a.W,d[2]*this.a.W])}this.Fa=b}else"mouseleave"==c&&(this.Fa=m)}};g.prototype.trigger=
g.prototype.d;j.b=g});
B("f14",["require","exports","module","f19","f35"],function(e,h,j){function g(a){"undefined"==typeof a&&(a=s);this.yd=0;this.wa=new c(0);this.yb=a;this.ef=0.1}var d=e("f19"),c=e("f35");g.prototype={Lb:function(a,b){"undefined"==typeof a&&(a=1==this.yd?0:1);this.yd=a;this.wa.set(a,this.yb,b)},t:function(a){var b=this.wa.get();return{transform:d.Y(1,1,this.ef),target:[{transform:d.Xa(Math.PI*b),target:a[0]},{transform:d.Xa(Math.PI*(b-
1)),target:a[1]}]}}};j.b=g});
B("f31",["require","exports","module"],function(e,h,j){function g(d,c){this.id=g.Ye++;this.p={};this.V={};this.content="";this.fa=v;this.classList=[];this.Ab=[];var a=this;this.Jb=function(b){a.d(b.type,b)};this.Hb=m;this.size=[0,0];"object"==typeof d&&this.vb(d);"undefined"!=typeof c&&this.Z(c);g.Td[this.id]=this}g.Ye=0;g.Td={};g.Xf=function(d){return g.Td[d]};g.Bd=["touchstart","touchmove","touchend","touchcancel","click"];g.prototype={t:function(){return this},bind:function(d,c){this.p.hasOwnProperty(d)||
(this.p[d]=[]);0>this.p[d].indexOf(c)&&this.p[d].push(c)},d:function(d,c){c&&(c.origin=this);this.Hb&&this.Hb.d(d,c);if(this.p.hasOwnProperty(d))for(var a=this.p[d],b=0;b<a.length;b++)a[b].call(this,c)},J:fa("Hb"),ub:function(d){for(n in d)d.hasOwnProperty(n)&&(this.V[n]=d[n],this.fa=s)},h:function(d){0>this.classList.indexOf(d)&&(this.classList.push(d),this.fa=s)},hc:function(d){d=this.classList.indexOf(d);0<=d&&(this.Ab.push(this.classList.splice(d,1)[0]),this.fa=s)},Z:function(d){this.content!=
d&&(this.content=d,this.fa=s)},Ie:function(d){for(var c in this.p)this.p.hasOwnProperty(c)&&d.addEventListener(c,this.Jb);c=g.Bd;for(var a=0;a<c.length;a++)d.addEventListener(c[a],this.Jb)},Qe:function(d){for(var c in this.p)this.p.hasOwnProperty(c)&&d.removeEventListener(c,this.Jb);c=g.Bd;for(var a=0;a<c.length;a++)d.removeEventListener(c[a],this.Jb)},pd:function(d){for(var c=0;c<this.Ab.length;c++)d.classList.remove(this.Ab[c]);this.Ab=[]},fd:function(d){this.size[0]&&(d.style.width=this.size[0]+
"px");this.size[1]&&(d.style.height=this.size[1]+"px");for(var c in this.V)this.V.hasOwnProperty(c)&&(d.style[c]=this.V[c]);c=this.classList;this.pd(d);for(var a=0;a<c.length;a++)d.classList.add(c[a]);d.innerHTML=this.content;this.Ie(d);this.fa=v;this.Na=d},Dc:function(d){d.style.width="";d.style.height="";for(var c in this.V)this.V.hasOwnProperty(c)&&(d.style[c]="");c=this.classList;this.pd(d);for(var a=0;a<c.length;a++)d.classList.remove(c[a]);this.Qe(d);this.Na=m},Sc:function(){return s},hf:function(){return this.Na&&
!this.size[0]&&!this.size[1]?[this.Na.offsetWidth,this.Na.offsetHeight]:this.size.slice(0)},vb:function(d){this.size=d.slice(0,2);this.fa=s}};j.b=g});
B("f5","require exports module f32 f31 f24".split(" "),function(e,h,j){function g(){c.apply(this,arguments);this.Pa=document.createElement("div");this.Pa.classList.add("group");this.pa=new d(this.Pa,{size:this.size});this.fa=s;this.Gb=m}var d=e("f32"),c=e("f31"),a=e("f24");g.prototype={fd:function(a){c.prototype.fd.apply(this,arguments);a.innerHTML="";a.style.webkitTransformStyle="flat";setTimeout(function(){a.style.webkitTransformStyle=
"preserve-3d";setTimeout(function(){a.style.webkitTransformStyle=""},0)},0)},Dc:function(a){a.style.webkitTransformStyle="flat";for(setTimeout(function(){a.style.webkitTransformStyle="preserve-3d";setTimeout(function(){a.style.webkitTransformStyle=""},0)},0);a.firstChild;)this.Pa.appendChild(a.removeChild(a.firstChild));c.prototype.Dc.apply(this,arguments)},update:function(a){this.pa.update(a);if(this.Na)for(;this.Pa.firstChild;)this.Na.appendChild(this.Pa.removeChild(this.Pa.firstChild))},t:function(a){!a&&
this.Gb&&(a=this.Gb.execute());this.update(a);return this},Gc:function(b){return this.Gb=new a(b)},jc:function(a){this.pa.jc(a)}};for(var b in c.prototype)c.prototype.hasOwnProperty(b)&&!g.prototype.hasOwnProperty(b)&&(g.prototype[b]=c.prototype[b]);j.b=g});
B("f28","require exports module f19 f35 f34".split(" "),function(e,h,j){function g(b){this.fc=b;this.u={};this.Uc={};for(var d in this.fc)this.u[d]=new a,this.u[d].Af({duration:1E3,m:c.r.mb})}var d=e("f19"),c=e("f35"),a=e("f34");g.prototype={k:function(a){this.u[a].k()},jf:function(a){for(var c=0;c<a.length;c++)this.k(c)},set:function(a,c,d,e){this.u[a].setTransform(c,d,e)},Ff:function(a,c,d,e){for(var g=
0;g<a.length;g++)this.set(a[g],c(g),d,0==g?e:m)},ab:function(a,c,d){this.Ff(this.all(),a,c,d)},modify:function(a,c,e,g){c=d.q(this.u[a].Mc,c);this.set(a,c,e,g)},tb:function(a,c,d,e){this.u[a].tb(c,d,e)},Df:function(a,c,d,e){for(var g=0;g<a.length;g++)this.tb(a[g],c,d,0==g?e:m)},ed:function(a,c,d){this.Df(this.all(),a,c,d)},all:function(){var a=[],c;for(c in this.fc)a.push(c);return a},F:function(a){return this.u[a].F()},Pc:function(a){return this.u[a].Pc()},Ub:function(a){this.Uc[a]=s},qc:function(a){this.Uc[a]=
v},Ud:function(a){return this.Uc[a]},Ta:function(a){return this.u[a].Ta()},t:function(){var a=[],c;for(c in this.fc)a.push(this.u[c].t(this.fc[c]));return a}};j.b=g});
B("f13",["require","exports","module","f19"],function(e,h,j){function g(c,a){this.kc=c;this.Eb=a;this.Ca=[];this.eb=[];this.Ac={}}var d=e("f19");g.prototype={Kc:function(c){0>this.Ca.indexOf(c)&&this.Ca.push(c);this.update()},Jf:function(c){c=this.Ca.indexOf(c);0<=c&&this.Ca.splice(c,1);this.update()},qe:function(c){this.Ca=c.slice(0);this.update()},Xe:function(c){var a=[],b;for(b in this.Eb)this.Eb.hasOwnProperty(b)&&0<=this.Eb[b].indexOf(c)&&a.push(b);return a},update:function(){for(var c=
[],a=0;a<this.Ca.length;a++)for(var b=this.Eb[this.Ca[a]],f=0;f<b.length;f++)0>c.indexOf(b[f])&&c.push(b[f]);for(var e=this.kc,g=[],b=[],a=0;a<this.eb.length;a++)f=this.eb[a],0>c.indexOf(f)&&(b.push(f),e.modify(f,d.c(0,0,this.Ac[f]),s),e.qc(f));for(a=0;a<c.length;a++)0>this.eb.indexOf(c[a])&&g.push(c[a]);b=[0,0,0];for(a=0;a<g.length;a++){var h=d.Da(e.F(g[a]));b[0]+=h[0];b[1]+=h[1];b[2]+=h[2]}b[0]/=g.length;b[1]/=g.length;b[2]/=g.length;for(var j=0,a=0;a<g.length;a++){var h=d.Da(e.F(g[a])),f=h[0]-
b[0],y=h[1]-b[1],h=h[2]-b[2],f=Math.sqrt(f*f+y*y+h*h);f>j&&(j=f);(function(a,b){var c=this;setTimeout(function(){var f=g[a];c.Ac[f]=1800*Math.pow(1-b/j,2)+200;e.Ub(f);e.modify(f,d.c(0,0,-c.Ac[f]),s)},3*b)}).call(this,a,f)}this.eb=c},mf:function(c){return 0<=this.eb.indexOf(c)}};j.b=g});
B("f17",["require","exports","module","f35"],function(e,h,j){function g(d,c){this.Sd=d;this.timeout=c;this.enabled=0<c;this.reset()}e("f35");g.prototype={enable:function(){this.enabled=s},disable:function(){this.enabled=v},update:function(){!this.ob&&(this.enabled&&this.Sd)&&(new Date).getTime()-this.nf>this.timeout&&(this.ob=s,this.Sd.call(this))},reset:function(){this.nf=(new Date).getTime();this.ob=v},d:function(){this.reset()}};j.b=g});
B("f16",["require","exports","module","f19","f35"],function(e,h,j){function g(a,b,c){"undefined"==typeof a&&(a=300);"undefined"==typeof b&&(b=2E3);"undefined"==typeof c&&(c=0.5);this.I=[];this.Qa=[];this.lf=a;this.duration=b;this.Oc=c;this.enabled=s}var d=e("f19"),c=e("f35");g.prototype={enable:function(){this.enabled=s},disable:function(){if(this.enabled){this.enabled=v;for(var a=0;a<this.I.length;a++)this.Ge(a)}},Kc:function(a){0>
this.Qa.indexOf(a)&&this.Qa.push(a)},kf:function(a){a=this.Qa.indexOf(a);0<=a&&this.Qa.splice(a,1)},qe:function(a){this.Qa=a.slice(0)},Ge:function(a,b){this.I.hasOwnProperty(a)&&("undefined"==typeof b&&(b=500),this.I[a].k(),this.I[a].set(0,{duration:b,m:c.r.mb}))},update:function(){if(this.enabled&&this.I.length&&!(Math.random()>this.Oc)){var a=Math.floor(Math.random()*this.I.length);if(!(0<=this.Qa.indexOf(a))){var b=Math.round(this.lf*(Math.random()-0.5)),d=Math.round(this.duration*(Math.random()+
0.5));this.I[a].k();this.I[a].set(b,{duration:d,m:c.r.mb})}}},t:function(a){this.update();for(var b=Array(a.length),f=0;f<a.length;f++){this.I.hasOwnProperty(f)||(this.I[f]=new c(0));var e=a[f];b[f]=e.transform?{transform:d.Ea(e.transform,[0,0,this.I[f].get()]),opacity:e.opacity,target:e.target}:{transform:d.c(0,0,this.I[f].get()),target:e}}return b}};j.b=g});
B("f15","require exports module f19 f35 f28".split(" "),function(e,h,j){function g(a,b){b||(b=0.1);this.kc=a;this.Oc=b}var d=e("f19"),c=e("f35");e("f28");g.prototype={If:function(a,b){var f=this.kc;f.Ub(a);f.Ub(b);var e=d.Da(f.F(a)),g=d.Da(f.F(b)),h=g[0]-e[0],j=g[1]-e[1],e=g[2]-e[2],g=100*Math.random()-50,y=100*Math.random()-50,q=100*Math.random()-50,l=100*Math.random()-50,C={duration:2E3,m:c.r.Ba},z={duration:1E3,
m:c.r.mb};f.modify(a,d.c(0,0,e),C);f.modify(a,d.c(h+g,0,0),C);f.modify(a,d.c(0,j+y,0),C);f.modify(a,d.c(-g,0,0),z);f.modify(a,d.c(0,-y,0),z,function(){f.qc(a)});f.modify(b,d.c(0,0,-e),C);f.modify(b,d.c(-h+q,0,0),C);f.modify(b,d.c(0,-j+l,0),C);f.modify(b,d.c(-q,0,0),z);f.modify(b,d.c(0,-l,0),z,function(){f.qc(b)})},update:function(){if(!(Math.random()>this.Oc)){var a=this.kc,b=a.all(),c=b[Math.floor(Math.random()*b.length)],b=b[Math.floor(Math.random()*b.length)];c==b||(a.Ta(c)||a.Ta(b)||a.Ud(c)||
a.Ud(b))||this.If(c,b)}}};j.b=g});
B("f9",["require","exports","module"],function(e,h,j){function g(d){this.state={position:0,i:0};this.gb={};this.K=[];this.Lc=0.5;this.Tc=1E-4;this.rf=1;this.pb=(new Date).getTime();this.za=v;this.set(d)}g.Ib=function(d){return function(c,a){return-d*c.i*c.i*a}};g.Mb=function(d){return function(c,a){return-d*Math.abs(c.i)*a}};g.lc=function(d,c,a){c||(c=0);a||(a=0);var b=2*a*Math.sqrt(c);return function(a,e){var g=a.position-d,h=g+a.i*e,j=0.5*c*g*g,y=0.5*c*h*h;return-(0>g/h?j:y-j)-
b*a.i*a.i*e}};g.bg=function(d,c){c||(c=0);return function(a,b){var f=a.position-d,e=f+a.i*b;if(0.5>Math.abs(f)&&0.5>Math.abs(e))return-0.5*a.i*a.i*b;f=-c/Math.max(Math.abs(f),0.5);return-(-c/Math.max(Math.abs(e),0.5)-f)}};g.prototype={set:function(d,c){d.hasOwnProperty("position")&&(this.state.position=d.position);d.hasOwnProperty("velocity")&&(this.state.i=d.i);c||(c=(new Date).getTime());this.pb=c;this.za=v},Za:function(d,c){0<=this.K.indexOf(d)&&(this.za=v);this.gb[d]=c},rc:function(d){this.jb(d);
this.gb.hasOwnProperty(d)&&delete this.gb[d]},da:function(d){this.gb.hasOwnProperty(d)&&0>this.K.indexOf(d)&&(this.K.push(d),this.za=v)},jb:function(d){d=this.K.indexOf(d);0<=d&&(this.K.splice(d,1),this.za=v)},zf:function(d){for(var c=0;c<this.K.length;c++)0>d.indexOf(this.K[c])&&this.jb(this.K[c]);for(c=0;c<d.length;c++)0>this.K.indexOf(d[c])&&this.da(d[c])},Md:function(d){this.update(d);return this.state},update:function(d){for(d||(d=(new Date).getTime());this.pb<d;){var c=d-this.pb;this.state.i&&
(c=Math.min(c,this.Lc/Math.abs(this.state.i)));c=Math.max(c,this.rf);this.Oe(c)}},vc:function(d,c){for(var a=0,b=0;b<this.K.length;b++)a+=this.gb[this.K[b]](d,c);return a},Oe:function(d){this.pb+=d;if(!this.za){var c=0,a=0;if(Math.abs(this.state.i)>this.Tc)c=this.vc(this.state,d),a=0<this.state.i?1:-1;else{var b=this.vc({position:this.state.position,i:this.Tc},d),f=this.vc({position:this.state.position,i:-this.Tc},d);b>f?(c=b,a=1):(c=f,a=-1);0>=b&&0>=f&&(this.za=s)}b=this.state.i;b=0.5*b*b+c;0>b?
(this.state.position+=this.state.i*d*(b/c),this.state.i=0):(c=a*Math.sqrt(2*Math.abs(b)),this.state.position+=this.state.i*d,this.state.i=c);this.za&&(this.state.position=Math.round(this.state.position/this.Lc)*this.Lc)}}};j.b=g});
B("f25",["require","exports","module","f19","f9"],function(e,h,j){function g(a,b){this.dir=a;this.a=b;this.a||(this.a={});this.a.Fd||(this.a.Fd=0.5);this.a.Zd||(this.a.Zd=50);this.a.Mb||(this.a.Mb=5E-5);this.a.Ib||(this.a.Ib=0.0010);this.a.Od||(this.a.Od=1);this.a.Jc||(this.a.Jc=2E-4);this.a.Ic||(this.a.Ic=1);this.a.bc||(this.a.bc=v);this.a.Yc||(this.a.Yc=0.1);this.a.he||(this.a.he=300);this.a.Zc||(this.a.Zc=1);this.a.ge||(this.a.ge=2E-4);this.a.fe||(this.a.fe=
1);this.a.Ec||(this.a.Ec="x"==this.dir?window.innerWidth:window.innerHeight);this.a.aa||(this.a.aa=0);this.a.U||(this.a.U=0);this.a.Nf&&(this.a.U=this.a.aa+this.a.Nf-this.a.Ec);this.p={};this.f=new c({position:0});this.Hb=this.Je();this.S=v;this.xa=[];this.yc=0;this.f.Za("friction",c.Mb(this.a.Mb));this.f.Za("drag",c.Ib(this.a.Ib));this.Gf(this.a.aa);this.Bf(this.a.U);this.Jd=[];this.vd=this.s=this.wc=0;this.Ef();this.disabled=v}var d=e("f19"),c=e("f9");g.prototype={bind:function(a,
b){this.p[a]||(this.p[a]=[]);b in this.p[a]||this.p[a].push(b)},Pe:function(a,b){if(this.p[a])for(var c=0;c<this.p[a].length;c++)this.p[a][c](b)},t:function(a){var b=this.f.Md(),f=b.position,b=b.i;if(this.a.bc){if(this.wc!=this.s){this.f.rc("page");if(0<=this.s){var e=Math.min(Math.max(this.a.rb[this.s],this.a.aa),this.a.U);this.f.Za("page",c.lc(e,this.a.ge,this.a.fe))}this.wc=this.s}0>this.s&&Math.abs(b)<this.a.Zc&&(this.s=this.Ad(f));(!this.S||0<=this.xa.indexOf("page"))&&this.f.da("page")}if(!this.S||
0<=this.xa.indexOf("edge"))if(f<this.a.aa||f>this.a.U)f<this.a.aa&&0>=b&&this.f.da("startSpring"),f>this.a.U&&0<=b&&this.f.da("endSpring"),this.f.jb("friction"),this.f.jb("drag"),this.a.bc&&this.f.jb("page");return{transform:"x"==this.dir?d.c(-f,0,0):d.c(0,-f,0),target:a,group:s}},Je:function(){var a=this,b={};return{d:function(c,d){if("touchmove"==c){for(var e=0,g=0;g<d.changedTouches.length;g++){var h=d.changedTouches[g];if(b.hasOwnProperty(h.identifier)){var j=b[h.identifier],q=h.pageX-j.x,l=h.pageY-
j.y,C=0;"x"==a.dir&&Math.abs(q)>Math.abs(l)?C=q:Math.abs(l)>Math.abs(q)&&(C=l);e-=C;j.x=h.pageX;j.y=h.pageY}}a.disabled||(d.preventDefault(),a.tf(e))}else if("touchstart"==c){if(!a.disabled){d.preventDefault();a.Ve();for(e=0;e<d.targetTouches.length;e++)g=d.targetTouches[e],b[g.identifier]={x:g.pageX,y:g.pageY}}}else if("touchend"==c)a:{for(e=0;e<d.changedTouches.length;e++)g=d.changedTouches[e],b.hasOwnProperty(g.identifier)&&delete b[g.identifier];for(e=0;e<d.touches.length;e++)if(b.hasOwnProperty(d.touches[e].identifier))break a;
d.preventDefault();a.Dd()}}}},disable:function(){this.disabled=s},enable:function(){this.disabled=v},O:function(){return this.f.Md().position},Nd:function(){return this.a.U-this.a.aa},Gf:function(a){this.a.aa=a;-Infinity<a?this.f.Za("startSpring",c.lc(a,this.a.Jc,this.a.Ic)):this.f.rc("startSpring")},Bf:function(a){this.a.U=a;Infinity>a?this.f.Za("endSpring",c.lc(a,this.a.Jc,this.a.Ic)):this.f.rc("endSpring")},Ue:function(a){a||(a=this.O());return a<=this.a.aa||a>=this.a.U},Ad:function(a){var b=0,
c=Infinity;for(i=0;i<this.a.rb.length;i++){var d=this.a.rb[i]-a;Math.abs(d)<c&&(b=i,c=Math.abs(d))}return b},Ef:function(a){if(Infinity>this.Nd()&&!a)for(var a=[],b=this.a.Ec,c=Math.round(this.Nd()/b),d=0;d<c;d++)a.push(d*b);this.a.rb=a;this.Pe("pageStopsChange")},z:function(a){this.f.set({position:a})},k:function(){this.f.set({i:0})},de:function(){this.f.zf([]);if(!this.S||0<=this.xa.indexOf("resist"))this.f.da("friction"),this.f.da("drag");if(!this.S||0<=this.xa.indexOf("external"))for(var a=0;a<
this.Jd.length;a++)this.Jd[a]&&this.f.da("external-"+a);if(this.S)for(a=0;a<this.xc.length;a++)this.f.da("link-"+a)},Ve:function(a,b){a||(a=[]);b||(b=[]);this.S&&this.Dd();0>a.indexOf("flow")&&this.k();this.S=s;this.xa=a;this.xc=b;for(var c=0;c<b.length;c++)this.f.Za("link-"+c,b[c]);this.de();this.Oa=0;this.zc=(new Date).getTime();return++this.yc},Dd:function(a){if(a&&a!=this.ff())return 0;(new Date).getTime()-this.zc>this.a.Zd&&(this.Oa=0);this.S=v;0>this.xa.indexOf("flow")&&this.f.set({i:this.Oa*
this.a.Od});this.xa=[];for(a=0;a<this.xc.length;a++)this.f.rc("link-"+a);this.xc=[];this.de();this.a.bc&&(a=this.Ad(this.O()),1<Math.abs(a-this.wc)&&(this.s=a),this.Oa>this.a.Yc?this.s++:this.Oa<-this.a.Yc?this.s--:this.s=a,0>this.s&&(this.s=0),this.s>=this.a.rb.length&&(this.s=this.a.rb.length-1),a=(new Date).getTime(),Math.abs(this.Oa)>this.a.Zc&&a-this.vd<this.a.he&&(this.s=-1),this.vd=a);return this.yc},ff:function(){return this.S?this.yc:0},tf:function(a){var b=this.Ue()?this.a.Fd*a:a;this.z(this.O()+
b);var b=(new Date).getTime(),c=b-this.zc;this.zc=b;c&&(this.Oa=a/c)}};j.b=g});
B("f23",["require","exports","module","f2"],function(e,h,j){function g(c,a){this.e=c;this.C=a&&a.C?a.C:0;this.Ia=a&&a.Ia?a.Ia:0;this.l=new d(this.e)}var d=e("f2");g.prototype={move:function(c,a,b){var d=this.e.O(),d=[d[0],d[1],d[2]+300],d=Math.max(Math.sqrt(d[0]*d[0]+d[2]*d[2]),300),e=c[0]/d;d<this.C&&(e=-e);this.l.o([0,e,0],a);this.l.move([0,c[1]+this.Ia*e,c[2]],a,b)},rotate:function(c,a,b){this.l.rotate(c,a,b)},o:function(c,a,b){this.l.move([0,
this.Ia*c[1],0],a);this.l.o(c,a,b)}};j.b=g});
B("f7",["require","exports","module","f8"],function(e,h,j){function g(c){this.T={};this.ib=c}var d=e("f8");g.prototype={ya:function(c,a){"undefined"==typeof this.ib&&this.oa(c);this.T[c]||(this.T[c]=new d);this.T[c].ya(a)},ic:function(c,a){this.T[c]&&this.T[c].ic(a)},N:function(c,a){"undefined"==typeof this.ib&&this.oa(c);this.T[c]||(this.T[c]=new d);this.T[c].N(a)},oa:fa("ib"),d:function(c,a){if("undefined"!=typeof this.ib){a||(a=
{});a.origin=this;var b=this.T[this.ib];b&&b.d(c,a)}}};j.b=g});
B("f33",["require","exports","module"],function(e,h,j){function g(d){this.touches={};this.Bb=v;this.a=d;this.a||(this.a={});this.a.De||(this.a.De=300);this.a.Qd||(this.a.Qd=300);"undefined"==typeof this.a.Fe&&(this.a.Fe=s);this.Gd=[]}g.prototype={ua:function(d){for(var c=this,a=0;a<d.changedTouches.length;a++){var b=d.changedTouches[a],e=b.identifier;this.touches[e]={le:b.pageX,me:b.pageY,timestamp:(new Date).getTime(),jd:0,kd:0};d.origin.d("grab");(function(a,b){c.touches[a].Rd=setTimeout(function(){b.d("hold",
{id:a})},c.a.Qd)}).call(this,e,d.origin)}this.Bb=1==d.touches.length;this.Gd=[]},ta:function(d){for(var c=(new Date).getTime(),a=0;a<d.changedTouches.length;a++){var b=d.changedTouches[a],e=b.identifier;if(this.touches[e]){var g=this.touches[e],h=b.pageX,b=b.pageY,j=h-g.le,w=b-g.me,y=c-g.timestamp,q=j/y,l=w/y;d.origin.d("move",{id:e,Tf:j,Uf:w,ld:q,ld:l,Ed:y});g.le=h;g.me=b;g.jd=q;g.kd=l;g.timestamp=c;clearTimeout(g.Rd)}}this.Bb=v},sa:function(d){for(var c=(new Date).getTime(),a=0;a<d.changedTouches.length;a++){var b=
d.changedTouches[a].identifier;if(this.touches[b]){var e=this.touches[b],g=c-e.timestamp;d.origin.d("release",{id:b,Of:e.jd,ld:e.kd,Ed:g});this.Bb&&g<this.a.De&&(g={id:b,Ed:g,target:d.target},d.origin.d("tap",g),this.a.Fe&&(d.preventDefault(),d.origin.d("click",g)));clearTimeout(e.Rd);this.Gd.push({id:b,Of:e.jd,ld:e.kd,timestamp:c});delete this.touches[b]}}0==d.touches.length&&(this.Bb=v)},d:function(d,c){"touchmove"==d?this.ta(c):"touchstart"==d?this.ua(c):"touchend"==d&&this.sa(c)}};j.b=g});
B("f22",["require","exports","module"],function(e,h,j){function g(){this.La={}}g.prototype={ua:function(d){this.Kb&&(this.ra=this.qa=m);for(var c=0;c<d.changedTouches.length;c++){var a=d.changedTouches[c];this.La[a.identifier]={x:a.pageX,y:a.pageY};"undefined"==typeof this.qa?this.qa=a.identifier:"undefined"==typeof this.ra&&(this.ra=a.identifier,this.Kb=s)}this.timestamp=(new Date).getTime();this.lb=this.od(this.La[this.qa],this.La[this.ra]);this.zb=0},ta:function(d){for(var c=
0;c<d.changedTouches.length;c++){var a=d.changedTouches[c];this.La[a.identifier]={x:a.pageX,y:a.pageY}}if(this.Kb&&"undefined"!=typeof this.qa&&"undefined"!=typeof this.ra){d=(new Date).getTime();c=d-this.timestamp;a=this.od(this.La[this.qa],this.La[this.ra]);if(10<c||0<c&&a!=this.lb)this.zb=(a-this.lb)/c;this.lb=a;this.timestamp=d}},sa:function(d){for(var c=(new Date).getTime(),a=0;a<d.changedTouches.length;a++){var b=d.changedTouches[a];this.qa==b.identifier&&(this.qa=m);this.ra==b.identifier&&
(this.ra=m);delete this.La[b.identifier]}this.Kb&&("undefined"==typeof this.qa&&"undefined"==typeof this.ra)&&(this.Kb=v,a=c-this.timestamp,300>a&&0>this.zb?d.origin.d("pinch",{Mf:this.zb,Ze:this.lb}):300>a&&0<this.zb&&d.origin.d("spread",{Mf:this.zb,Ze:this.lb}));this.timestamp=c},od:function(d,c){if(d&&c){var a=c.x-d.x,b=c.y-d.y;return Math.sqrt(a*a+b*b)}},d:function(d,c){"touchstart"==d?this.ua(c):"touchmove"==d?this.ta(c):"touchend"==d&&this.sa(c)}};j.b=g});
B("f27",["require","exports","module"],function(e,h,j){function g(){this.Hf=this.startTime=0;this.na=[];this.Q=-1}g.prototype={sd:function(d){0>this.Q&&(this.Q=0);for(;this.Q<this.na.length&&this.na[this.Q].gc<=d;)this.na[this.Q].action.call(this),this.Q++},update:function(){0>this.Q||this.Q>=this.na.length||this.sd((new Date).getTime()-this.startTime)},hb:function(d,c){this.na.push({gc:d,action:c});this.Hf=d},play:function(d){this.na.sort(function(a,b){return a.gc-b.gc});this.startTime=
(new Date).getTime();for(var c=0;c<this.na.length&&this.na[c].gc<d;)c++;this.Q=c},Ld:function(d){"undefined"==typeof d&&(d=Infinity);this.sd(d)},stop:function(){this.Q=-1}};j.b=g});
B("elements",{df:"施 瑾 言 李 心 怡 解 正 军 李 硕 张 权 黄 明 倩 尚 远 远 周 良 张 皓 南 严 晓 沁 池 嘉 明 蒋 征 骐 周 韦 秋 韩 峥 润 朱 海 蒙 陆 佳 杰 储 天 骄 陆 嘉 胜 吴 怡 董 笑 林 刘 梦 凡 陈 宇 星 王 思 佳 李 林 波 顾 海 锋 邹 静 孙 萌 刘 煜 张 金 肖 袁 钟 柱 高 帆 蒋 文 刘 颖 章 晨 亮 李 尧 张 金 肖 张 金 肖 张 金 肖 张 金 肖 张 金 肖 张 金 肖 张 金 肖 张 金 肖 张 金 肖 张 金 肖 张 金 肖 张 金 肖 张 金 肖 张 金 肖".split(" "),af:{eg:[0,5,6,7,14,15,33],dg:[1,9,17,35,53,85,117],Zf:[8,16,34,52,84,116],cg:[4,13,31,32,50,51,83],yb:[20,21,22,23,24,25,26,27,28,
29,38,39,40,41,42,43,44,45,46,47,71,72,73,74,75,76,77,78,79,103,104,105,106,107,108,109,110,111],fg:[12,30,48,49,80,81,82,112,113,114,115],Qf:[2,10,18,36,54,86],Rf:[3,11,19,37,55,87],ag:[56,57,58,59,60,61,62,63,64,65,66,67,68,69,70],Pf:[88,89,90,91,92,93,94,95,96,97,98,99,100,101,102]},cf:"Hydrogen Helium Lithium Beryllium Boron Carbon Nitrogen Oxygen Fluorine Neon Sodium Magnesium Aluminium Silicon Phosphorus Sulfur Chlorine Argon Potassium Calcium Scandium Titanium Vanadium Chromium Manganese Iron Cobalt Nickel Copper Zinc Gallium Germanium Arsenic Selenium Bromine Krypton Rubidium Strontium Yttrium Zirconium Niobium Molybdenum Technetium Ruthenium Rhodium Palladium Silver Cadmium Indium Tin Antimony Tellurium Iodine Xenon Cesium Barium Lanthanum Cerium Praseodymium Neodymium Promethium Samarium Europium Gadolinium Terbium Dysprosium Holmium Erbium Thulium Ytterbium Lutetium Hafnium Tantalum Tungsten Rhenium Osmium Iridium Platinum Gold Mercury Thallium Lead Bismuth Polonium Astatine Radon Francium Radium Actinium Thorium Protactinium Uranium Neptunium Plutonium Americium Curium Berkelium Californium Einsteinium Fermium Mendelevium Nobelium Lawrencium Rutherfordium Dubnium Seaborgium Bohrium Hassium Meitnerium Darmstadtium Roentgenium Copernicium Ravikantium Flerovium Ununpentium Livermorium Ununseptium Urasium".split(" "),
bf:"1.008;4.003;6.941;9.012;10.812;12.011;14.007;15.999;18.998;20.180;22.990;24.305;26.982;28.086;30.974;32.066;35.453;39.948;39.098;40.078;44.956;47.867;50.942;51.996;54.938;55.845;58.933;58.693;63.546;65.382;69.723;72.631;74.922;78.963;79.904;83.798;85.468;87.621;88.906;91.224;92.906;95.962;(98);101.072;102.916;106.421;107.868;112.411;114.818;118.712;121.760;127.603;126.904;131.294;132.905;137.328;138.905;140.116;140.908;144.242;(145);150.362;151.964;157.253;158.925;162.500;164.930;167.259;168.934;173.055;174.967;178.492;180.948;183.841;186.207;190.233;192.217;195.085;196.967;200.592;204.383;207.21;208.980;(209);(210);(222);(223);(226);(227);232.038;231.036;238.029;(237);(244);(243);(247);(247);(251);(252);(257);(258);(259);(262);(267);(268);(269);(270);(269);(278);(281);(281);(285);Angellist Maximus;(289);(288);(293);(294);Michael Arrington".split(";")});
B("app","require exports module f10 f4 f12 f34 f0 f1 f30 f29 f21 f18 f20 f14 f31 f5 f28 f13 f17 f16 f15 f25 f23 f19 f34 f35 f7 f8 f33 f22 f11 f27 elements elements elements elements".split(" "),
function(e){function h(a){117==a?a=62:62==a&&(a=117);return r.c(ia*(Math.floor(a/15)-3.5),ja*(a%5-2),-ya*(Math.floor(a/5)%3)-500)}function j(a){0==a?a=112:112==a&&(a=0);return jb(a)}function g(a){if(1>a)a=[0,0];else if(2>a)a=[17,0];else if(4>a)a=[a-2,1];else if(10>a)a=[a+8,1];else if(12>a)a=[a-10,2];else if(18>a)a=[a,2];else if(36>a)a=[a-18,3];else if(54>a)a=[a-36,4];else if(56>a)a=[a-54,5];else if(71>a)a=[a-53,8];else if(86>a)a=[a-68,5];else if(88>a)a=[a-86,6];else if(103>a)a=[a-85,9];else if(118>
a)a=[a-100,6];else return r.Y(0,0,0);return r.c(150*(a[0]-8.5),190*(a[1]-4.5),0)}function d(a){return r.q(r.c(0,20*(a-59),700),r.Xa(0.1*a*Math.PI))}function c(a){return r.q(r.c(0,250*(Math.floor(a/30)-1),-900),r.Xa(-0.06667*a*Math.PI))}function a(a,b){-1==H&&(u.ed(1),ka.ia());H="undefined"!=typeof a?a:(H+1)%5;0<=J&&k(J);p.k();var e={duration:1E3,m:M.r.Ba};0==H?(u.ab(g,e,b),p.z([0,0,700],e),p.A([0,0,0],e),p.D([0,0,0],e)):3==H?(p.z([0,0,800],e),p.A([0,0,0],e),p.D([0,0,0],e),u.ab(j,e,b)):4==H?(p.z([0,
0,-600],e),p.A([0,-Math.PI/6,0],e),p.D([0,0,0],e),u.ab(h,e,b)):1==H?(p.z([0,0,700],e),p.A([0,0,0],e),p.D([0,0,0],e),u.ab(d,e,b)):2==H&&(p.z([0,0,-500],e),p.A([0,0,0],e),p.D([0,0,0],e),u.ab(c,e,b));4==H?S.enable():S.disable();T.oa(H)}function b(){var a={duration:1E3};k(J);p.z(Na,a);p.A(kb,a);p.D(Oa,a)}function f(a){r.ja(u.F(a));J=a;lb=u.F(a);u.Ub(a);la.oa(1);var b=N[a].V.backgroundImage;if(b){N[a].ub({backgroundImage:O[a].V.backgroundImage});var c=new Image;c.onload=function(){N[a].ub({backgroundImage:b})};
c.src=b.substring(5,b.length-2)}Na=p.O().slice(0);kb=p.ga().slice(0);Oa=p.Ra().slice(0);$.ub({backgroundColor:O[a].V.backgroundColor});c=r.q(r.c(0,0,-200),u.F(a));p.qf(c,{duration:1E3},function(){J==a&&(u.set(a,r.Y(0,0,0)),w.be(function(){Pa.show()}))});S.Kc(a);S.Ge(a,500);L.disable()}function k(a){ma.Lb(0);u.set(a,lb);u.qc(a);S.kf(a);J==a&&(L.enable(),J=-1,la.oa(0),Pa.ia())}function I(){za.ia();na.oa(0);x=s}document.title="Periodic Table";if(!("WebKitCSSMatrix"in window)||!("m11"in new WebKitCSSMatrix))window.location.href=
"http://famo.us/compat";var x=v,w=e("f10"),y=e("f4"),q=e("f12"),l=e("f34"),C=e("f0");e("f1");var z=e("f30"),X=e("f29"),F=e("f21"),R=e("f18"),Y=e("f20"),Z=e("f14"),A=e("f31");e("f5");var ha=e("f28"),zb=e("f13"),Ab=e("f17"),Bb=e("f16"),
Cb=e("f15");e("f25");var aa=e("f23"),r=e("f19"),l=e("f34"),M=e("f35"),Qa=e("f7");e("f8");var G=e("f33");e("f22");for(var mb=e("f11"),nb=e("f27"),Ra=e("elements").df,Db=e("elements").af,ob=e("elements").cf,pb=e("elements").bf,oa=Ra.length,Sa=Array(oa),Ta=0;Ta<oa;Ta++)Sa[Ta]=0.1+0.7*Math.random();for(var O,
Ua=Array(oa),P=0;P<Ua.length;P++){var Aa=new A([120,160]);Aa.ub({backgroundColor:"rgba(73,160,154,"+Sa[P]+")"});Aa.h("periodic-item");Aa.Z('<div class="number">'+(P+1)+'</div><div class="symbol">'+Ra[P]+'</div><div class="name">'+ob[P]+'</div><div class="mass">'+pb[P]+"</div>");Ua[P]=Aa}O=Ua;for(var N,Va=Array(oa),Q=0;Q<Va.length;Q++){var Ba=new A([360,480]);Ba.ub({backgroundColor:"rgba(73,160,154,"+Sa[Q]+")"});Ba.h("periodic-item-hq");Ba.Z('<div class="number">'+(Q+1)+'</div><div class="symbol">'+
Ra[Q]+'</div><div class="name">'+ob[Q]+'</div><div class="mass">'+pb[Q]+"</div>");Va[Q]=Ba}N=Va;var p=new C;p.z([0,0,5E3]);p.A([0,0,0]);p.D([0,-3*Math.PI,0]);var Eb=new z(p),Fb=new X(p,{C:700,R:2*Math.PI,P:2*Math.PI,bd:500,gd:500}),Gb=new F(p),Hb=new z(p,{C:900,v:aa}),Ib=new z(p,{C:700,Ia:200/Math.PI,v:aa}),Jb=new R(p),qb=new R(p,{o:s}),Kb=new R(p,{C:700,Ia:200/Math.PI,o:s,ka:s,v:aa}),Lb=new R(p,{C:900,o:s,v:aa}),Mb=new Y(p),rb=new Y(p,{o:s}),Nb=new Y(p,{C:700,Ia:200/Math.PI,o:s,ka:s,v:aa}),Ob=new Y(p,
{C:900,o:s,v:aa}),U=new nb;w.Db(U);U.hb(0,function(){L.disable();p.k();p.z([0,0,700],{duration:16E3,m:M.r.Hc})});for(var D=0;D<O.length;D++)(function(a,b){U.hb(b,function(){u.tb(a,1,{duration:500,m:M.r.Ba});var b=r.Da(u.F(a)),c=-p.O()[2]+500*Math.random(),d=1E3*Math.random()-500-b[0],b=1E3*Math.random()-500-b[1],e=r.c(-d,0,0),f=r.c(0,-b,0),g=r.c(0,0,-c),h=Math.abs(d)<Math.abs(b);u.modify(a,r.c(d,b,c));u.modify(a,g,{duration:Math.max(0.5*Math.abs(c),2E3)*(Math.random()+1.6),m:M.r.mb});u.modify(a,h?
e:f,{duration:1E3*Math.random()+500,m:M.r.Hc});u.modify(a,h?f:e,{duration:1E3*Math.random()+500,m:M.r.Hc})})}).call(this,D,16E3*Math.random());U.hb(14E3,function(){p.D([0,0,0],{duration:7E3,m:M.r.Ba},function(){L.reset();L.enable()})});var L=new Ab(function(){function b(){d.ob&&setTimeout(function Pb(){if(d.ob){var a=p.ga().slice(0),b=a.slice(0),c=0.5>Math.random()?-1:1;0.5>Math.random()?b[0]+=2*c*Math.PI:b[1]+=2*c*Math.PI;p.A(b,{duration:3E3},function(){p.A(a);setTimeout(Pb,1E4)})}},1E4)}function c(){d.ob&&
(u.jf(u.all()),a(4,b))}var d=this;3==H?c():(a(3),setTimeout(c,200))},15E3);L.disable();w.Db(L);w.ya(L);var S=new Bb(300,2E3,1);S.disable();for(var ia=270,ja=350,ya=400,jb,Ca=[],sb=Math.floor(7),Wa=0;Wa<=sb;Wa++){var tb=Math.PI/2-Wa*(Math.PI/sb),Da=Math.floor(1400*Math.PI*Math.cos(tb)/160);0==Da&&(Da=1);for(var Xa=0;Xa<Da;Xa++)Ca.push(r.q(r.c(0,0,700),r.pe(tb),r.Xa(Xa*(2*Math.PI/Da)-Math.PI)))}for(;118>Ca.length;)Ca.push(r.L);jb=function(a){return 118<=a?r.Y(0,0,0):Ca[a]};var T=new Qa(-1);T.N(0,[Eb,
qb,rb]);T.N(3,[Fb,qb,rb]);T.N(4,[Gb,Jb,Mb]);T.N(1,[Ib,Kb,Nb]);T.N(2,[Hb,Lb,Ob]);var ub=new mb;ub.Va("keypress",function(b){x&&32==b.keyCode&&a()});var H=-1,Ya=new mb([new G]);Ya.Va("click",function(a){a.target==document.body&&b()});Ya.Va("keyup",function(a){27==a.keyCode?b():32==a.keyCode&&ma.Lb()});var la=new Qa(0),u=new ha(O);u.ab(g);u.ed(0);for(var Qb=new Cb(u,0.1),pa=new zb(u,Db),Pa=new q(0,v),ma=new Z,J=-1,Na=m,kb=m,Oa=m,lb=m,D=0;D<O.length;D++)(function(a,b){b.J(new G);b.bind("click",function(){x&&
(0>J?f(a):(k(J),f(a),Na=[0,0,600],beforeRotate=[0,0,0],Oa=[0,0,0]))});b.bind("hold",function(){if(x){var b=pa.Xe(a)[0];pa.mf(a)?pa.Jf(b):pa.Kc(b)}})}).call(this,D,O[D]);for(D=0;D<N.length;D++)N[D].J(new G),N[D].bind("click",function(){ma.Lb(1)});new M(0);var $=new A([360,480],"Reserved for Future Examples");$.h("periodic-item-hq");$.h("periodic-item-back");$.J(new G);$.bind("click",function(){ma.Lb(0)});var vb=new A([200,32],"periodic table");vb.h("caption");var ka=new q(1),Ea=new A([200,200]);Ea.h("play-button");
Ea.J(new G);Ea.bind("click",function(){ka.Sc(1)&&(U.play(),qa.play(),ka.ia(),sessionStorage.setItem("sequenceViewed",s))});var ba=new A([60,60],"&#10148;");ba.h("bottom-button");ba.J(new G);ba.bind("click",function(){x&&(qa.Ld(),w.be(function(){a()}))});var ca=new A([60,60],"&#9638;");ca.h("bottom-button");ca.J(new G);ca.bind("click",function(){x&&(U.stop(),qa.Ld(),pa.qe([]),u.ed(1,s),a(4),L.enable(),ka.ia())});var da=new A([60,60],"&#8634;");da.h("bottom-button");da.J(new G);da.bind("click",function(){x&&
window.location.reload()});var ea=new A([60,60],"&#9432;");ea.h("info-button");var za=new q;ea.J(new G);ea.bind("click",function(){x&&(za.show(),na.oa(1))});sessionStorage.getItem("sequenceViewed")?x=s:(x=v,ba.h("inactive"),ca.h("inactive"),da.h("inactive"),ea.h("inactive"));var Fa=new A([600,500],'<h3>Fun Things to Do</h3><ul><li>One finger to scroll</li><li>Two fingers to pinch zoom</li><li>Three fingers to plane in 3D</li><li>Touch any object to navigate to that object in 3D space</li><li>Touch-hold an object to disassemble any shape</li></ul><ul><li>&#10148; or Space key to switch shape</li><li>&#9638; to return to paraflow</li><li>&#8634; to reset to start sequence</ul><ul><li>WASD keys to move forward, left, backward, and right</li><li>Shift + W/S keys to move up/down</li><li>Arrow keys to rotate or spin</li></ul><div class="control"><button>Begin</button></div>');
Fa.h("info");Fa.J(new G);Fa.bind("click",I);var ra=new A([window.innerWidth,window.innerHeight]);ra.h("info-obscure");ra.J(new G);ra.bind("click",I);var Za=new y;Za.n(new l(r.c(0,0,0.2))).g(Fa);Za.n(new l(r.c(0,0,0.1))).g(ra);var na=new Qa(0);na.ya(0,la);var sa=new A([100,60],"famo.us");sa.h("overlay-text");sa.h("clickable-text");sa.J(new G);sa.bind("click",function(){window.location.href="http://famo.us"});var Ga=new A([500,150]);Ga.h("signup-box");Ga.Z('<p>performance has been solved for HTML5 apps</p><form method="POST" action="#"><input id="email" type="text" size="30" name="email" maxlength="75" placeholder="enter email to sign up for beta" size="35" /><input class="button" type="submit" value="sign up" /></form>');
window.addEventListener("submit",function(a){a.preventDefault();for(var b={},a=a.target.querySelectorAll("input"),c=0;c<a.length;c++){var d=a[c];d.name&&(b[d.name]=d.value)}a=document.location.href.split("/");b.referrerId=2<=a.length&&"r"==a[a.length-2]?a[a.length-1]:"";a=new XMLHttpRequest;a.open("POST","/developers");a.setRequestHeader("Content-Type","application/json");a.onreadystatechange=function(){if(4==this.readyState)if(200==this.status){var a=JSON.parse(this.responseText);"OK"==a.status?
(ta.Z(""),Ga.Z('<p class="success">Success!</p><p>We just sent you an email with some more information.  We\'ll send you updates soon.</p>')):ta.Z(a.msg)}else ta.Z("Ooops! Something went wrong. Try again.")};a.send(JSON.stringify(b))});var ta=new A([500,18]);ta.h("signup-error");var $a=new q(1),ab=new q(0),Ha=new A([30,30],"&#8855;");Ha.h("signup-hide");Ha.J(new G);Ha.bind("click",function(){$a.ia();ab.show()});var Ia=new A([120,30],"sign up");Ia.h("overlay-text");Ia.h("clickable-text");Ia.bind("click",
function(){$a.show();ab.ia()});var Ja=new y;Ja.n(new l(r.L,1,"t")).g(Ga);Ja.n(new l(r.c(0,120,0.1),1,"t")).g(ta);Ja.n(new l(r.c(230,0,0.1),1,"t")).g(Ha);var qa=new nb;w.Db(qa);var bb=new A([500,60],"Try this demo on phones, tablets, computers, and Samsung Smart TVs");bb.h("ticker-text");for(var cb=new q(1),db="This is not a movie...{This is not WebGL...{This is not Canvas...{There are no CSS3 transitions...{Everything is real DOM...{Less than 60KB...{Imagine what you could create...{This is famo.us.{You may now play!{快来找你的名字".split("{"),
D=0;D<db.length;D++)(function(a){qa.hb(3E3*a,function(){cb.ia(function(){bb.Z(db[a]);cb.show()})})}).call(this,D);U.hb(3E3*(db.length-1),function(){ba.hc("inactive");ca.hc("inactive");da.hc("inactive");ea.hc("inactive");za.show();na.oa(1);a(4)});var Rb=w.Cd(document.querySelector("#main")),wb=w.Cd(document.querySelector("#overlay")),eb=new y;eb.n(new l(r.Ea(r.Y(3,3,3),[0,-1E3,0]))).g(vb);eb.n(S).g(u);var Ka=new y;Ka.n(p).g(eb);Ka.n(ka).g(new l(r.L,0.3)).g(Ea);Ka.n(Pa).g(new l(r.c(0,0,200))).g(ma).g(function(){return[{transform:r.Y(0.333333,
0.333333,0.333333),target:0<=J?N[J]:t},{transform:r.Y(0.333333,0.333333,0.333333),target:$}]});var fb=new A([window.innerWidth,60]);fb.h("bottom-bar");wb.Va("resize",function(){fb.vb([window.innerWidth,60]);ra.vb([window.innerWidth,window.innerHeight])});var K=new y;K.n(new l(r.L,1,"tr")).g(ea);K.n(new l(r.c(0,0,0.1))).g(za).g(Za);K.n(new l(r.c(-120,0,0),1,"br")).g(ba);K.n(new l(r.c(-60,0,0),1,"br")).g(ca);K.n(new l(r.L,1,"br")).g(da);K.n(new l(r.L,1,"bl")).g(sa);K.n(new l(r.c(0,0,-0.1),1,"b")).g(fb);
K.n(new l(r.L,1,"tl")).g(ab).g(Ia);K.n($a).g(Ja);K.n(new l(r.L,1,"b")).g(cb).g(bb);Rb.Gc(Ka);wb.Gc(K);la.N(0,[T,ub]);la.N(1,[Ya]);w.ya(na);w.Db(function(){if(4==H){for(var a=Math.ceil(oa/15),b=p.O(),c=p.ga(),d=0.5*Math.abs(Math.sin(c[1])+1),c=0.5*Math.abs(-Math.sin(c[0])+1),e=0;e<O.length;e++)if(!u.Ta(e)){var f=u.F(e),g=r.Da(f),g=[-b[0]+g[0],-b[1]+g[1],-b[2]+g[2]],h=[0,0,0];g[0]<(d-1)*a*ia&&(h[0]=a*ia);g[0]>d*a*ia&&(h[0]=-a*ia);g[1]<5*(c-1)*ja&&(h[1]=5*ja);g[1]>5*c*ja&&(h[1]=-5*ja);g[2]<-3*ya+200&&
(h[2]=3*ya);300<g[2]&&(h[2]=-3*ya);u.set(e,r.Ea(f,h))}Qb.update()}})});ga(["app"]);

