city_dict = {'德阳': 'deyang', '广州': 'guangzhou', '杭州': 'hangzhou', '厦门': 'xiamen', '内江': 'neijiang', '揭阳': 'jieyang',
             '延安': 'yanan', '大同': 'datong', '吕梁': 'lvliang', '雅安': 'yaan', '文昌': 'wenchang', '南平': 'nanping',
             '北海': 'beihai', '贵港': 'guigang', '鸡西': 'jixi', '开封': 'kaifeng', '红河': 'honghe', '信阳': 'xinyang',
             '阳江': 'yangjiang', '宣城': 'xuancheng', '连云港': 'lianyungang', '六盘水': 'liupanshui', '怀化': 'huaihua',
             '云浮': 'yunfu', '盐城': 'yancheng', '濮阳': 'puyang', '伊犁': 'yili', '保定': 'baoding', '湖州': 'huzhou',
             '呼伦贝尔': 'hulunbeier', '陵水': 'lingshui', '广元': 'guangyuan', '无锡': 'wuxi', '东莞': 'dongguan', '吉林': 'jilin',
             '亳州': 'bozhou', '昌都': 'changdudiqu', '沈阳': 'shenyang', '梧州': 'wuzhou', '固原': 'guyuan', '玉溪': 'yuxi',
             '天门': 'tianmen', '泰安': 'taian', '遵义': 'zunyi', '昌江': 'changjiang', '郑州': 'zhengzhou', '菏泽': 'heze',
             '葫芦岛': 'huludao', '南宁': 'nanning', '石家庄': 'shijiazhuang', '黑河': 'heihe', '荆门': 'jinmen', '四平': 'siping',
             '盘锦': 'panjin', '合肥': 'hefei', '绵阳': 'mianyang', '贺州': 'hezhou', '黄石': 'huangshi', '娄底': 'loudi',
             '北屯': 'beitun', '金昌': 'jinchang', '泉州': 'quanzhou', '太原': 'taiyuan', '乐山': 'leshan', '五指山': 'wuzhishan',
             '丹东': 'dandong', '鹤岗': 'hegang', '攀枝花': 'panzhihua', '周口': 'zhoukou', '南充': 'nanchong', '北京': 'beijing',
             '锦州': 'jinzhou', '济宁': 'jining', '河池': 'hechi', '阜阳': 'fuyang', '运城': 'yuncheng', '株洲': 'zhuzhou',
             '湘西': 'xiangxi', '重庆': 'chongqing', '张掖': 'zhangye', '赣州': 'ganzhou', '甘南': 'gannan', '烟台': 'yantai',
             '茂名': 'maoming', '三明': 'sanming', '宁德': 'ningde', '庆阳': 'qingyang', '邢台': 'xingtai',
             '承德': 'chengde', '安康': 'ankang', '日照': 'rizhao', '鞍山': 'anshan', '安顺': 'anshun', '新余': 'xinyu',
             '咸阳': 'xianyang', '白山': 'changbaishan', '丽江': 'lijiang', '哈密': 'hami', '阿里': 'ali', '曲靖': 'qujing',
             '惠州': 'huizhou', '巴音郭楞': 'bayinguoleng', '德州': 'dezhou', '临沧': 'linchang', '乌海': 'wuhai', '日喀则': 'rikaze',
             '和田': 'hetian', '桂林': 'guilin', '聊城': 'liaocheng', '宜春': 'yichun', '哈尔滨': 'haerbin',
             '长治': 'changzhi', '乐东': 'ledong', '阿拉尔': 'alaer', '阳泉': 'yangquan', '塔城': 'tacheng', '漯河': 'luohe',
             '黄山': 'huangshan', '陇南': 'longnan', '百色': 'baise', '海南州': 'hainanzhou', '安庆': 'anqing', '商洛': 'shangluo',
             '临汾': 'linfen', '恩施': 'enshi', '永州': 'yongzhou', '徐州': 'xuzhou', '甘孜州': 'ganzi', '万宁': 'wanning',
             '牡丹江': 'mudanjiang', '昭通': 'zhaotong', '益阳': 'yiyang', '乌兰察布': 'wulanchabu', '上海': 'shanghai',
             '定西': 'dingxi', '琼中': 'qiongzhong', '石河子': 'shihezi', '成都': 'chengdu', '平凉': 'pingliang', '渭南': 'weinan',
             '金华': 'jinhua', '铁岭': 'tieling', '天津': 'tianjin', '博尔塔拉': 'boertala', '温州': 'wenzhou',
             '安阳': 'anyang', '黔南': 'qiannan', '营口': 'yingkou', '九江': 'jiujiang', '荆州': 'jingzhou',
             '晋城': 'jincheng', '淮南': 'huainan', '仙桃': 'xiantao', '吉安': 'jian', '阿克苏': 'akesu', '铜川': 'tongchuan',
             '上饶': 'shangrao', '三沙': 'sansha', '肇庆': 'zhaoqing', '潍坊': 'weifang', '三亚': 'sanya', '铜陵': 'tongling',
             '滨州': 'binzhou', '武威': 'wuwei', '泸州': 'luzhou', '宜宾': 'yibin', '莱芜': 'laiwu', '漳州': 'zhangzhou',
             '济南': 'jinan', '玉林': 'yulin', '廊坊': 'langfang', '普洱': 'puer', '珠海': 'zhuhai', '许昌': 'xuchangxian',
             '韶关': 'shaoguan', '定安': 'dingan', '兰州': 'lanzhou', '鹰潭': 'yingtan', '十堰': 'shiyan', '屯昌': 'tunchang',
             '孝感': 'xiaogan', '池州': 'chizhou', '淮北': 'huaibei', '郴州': 'chenzhou', '威海': 'weihai', '梅州': 'meizhou',
             '随州': 'suizhou', '鄂尔多斯': 'eerduosi', '抚顺': 'fushun', '保山': 'baoshan', '东方': 'dongfang', '江门': 'jiangmen',
             '南京': 'nanjing', '神农架': 'shennongjia', '丽水': 'lishui', '南昌': 'nanchang', '榆林': 'yulin',
             '邵阳': 'shaoyang', '中山': 'zhongshan', '鄂州': 'ezhou', '克拉玛依': 'kelamayi', '抚州': 'jiangxifuzhou',
             '保亭': 'baoting', '儋州': 'danzhou', '伊春': 'yichun', '新乡': 'xinxiang', '沧州': 'cangzhou',
             '呼和浩特': 'huhehaote', '酒泉': 'jiuquan', '大庆': 'daqing', '湛江': 'zhanjiang', '潜江': 'qianjiang',
             '那曲': 'naqu', '洛阳': 'luoyang', '唐山': 'tangshan', '河源': 'heyuan', '汉中': 'hanzhong', '汕尾': 'shanwei',
             '嘉峪关': 'jiayuguan', '苏州': 'suzhou', '崇左': 'chongzuo', '武汉': 'wuhan', '常州': 'changzhou', '深圳': 'shenzhen',
             '临夏': 'linxia', '衡阳': 'hengyang', '扬州': 'yangzhou', '朝阳': 'chaoyang', '吐鲁番': 'tulufan',
             '佛山': 'foshan', '辽源': 'liaoyuan', '宝鸡': 'baoji', '白沙': 'baisha', '山南': 'shannan', '莆田': 'putian',
             '延边': 'yanbian', '天水': 'tianshui', '本溪': 'benxi', '枣庄': 'zaozhuang', '朔州': 'shuozhou', '海口': 'haikou',
             '白城': 'baicheng', '长春': 'changchun', '汕头': 'shantou', '钦州': 'qinzhou', '衡水': 'hengshui', '柳州': 'liuzhou',
             '阿勒泰': 'aletai', '铜仁': 'tongren', '三门峡': 'sanmenxia', '蚌埠': 'bengbu', '佳木斯': 'jiamusi', '通辽': 'tongliao',
             '张家界': 'zhangjiajie', '邯郸': 'handan', '大兴安岭': 'daxinganling', '清远': 'qingyuan', '宿迁': 'suqian',
             '焦作': 'jiaozuo', '龙岩': 'longyan', '宁波': 'ningbo', '鹤壁': 'hebi', '克孜勒苏': 'kezilesu', '黔东南': 'qiandongnan',
             '昌吉': 'changji', '贵阳': 'guiyang', '西安': 'xian', '辽阳': 'liaoyang', '楚雄': 'chuxiong',
             '秦皇岛': 'qinhuangdao', '济源': 'jiyuan', '宿州': 'anhuisuzhou', '巴彦淖尔': 'bayannaoer', '达州': 'dazhou',
             '来宾': 'laibin',
             '拉萨': 'lasa', '石嘴山': 'shizuishan', '资阳': 'ziyang', '铁门关': 'tiemenguan', '乌鲁木齐': 'wulumuqi',
             '喀什': 'kashi', '衢州': 'quzhou', '福州': 'fuzhou', '湘潭': 'xiangtan', '岳阳': 'yueyang', '林芝': 'linzhi',
             '自贡': 'zigong', '白银': 'baiyin', '琼海': 'qionghai', '澄迈': 'chengmai', '临高': 'lingao', '淮安': 'huaian',
             '银川': 'yinchuan', '宜昌': 'yichang', '遂宁': 'suining', '松原': 'songyuan', '淄博': 'zibo', '临沂': 'linyi',
             '眉山': 'emeishan', '忻州': 'xinzhou', '图木舒克': 'tumushuke', '通化': 'tonghua', '巴中': 'bazhong',
             '大连': 'dalian', '晋中': 'jinzhong', '平顶山': 'pingdingshan', '五家渠': 'wujiaqu', '绍兴': 'shaoxing',
             '广安': 'guangan', '南阳': 'nanyang', '西宁': 'xining', '景德镇': 'jingdezhen', '襄阳': 'xiangyang', '六安': 'liuan',
             '齐齐哈尔': 'qiqihaer', '海东': 'haidong', '咸宁': 'xianning', '七台河': 'qitaihe', '商丘': 'shangqiu', '吴忠': 'wuzhong',
             '萍乡': 'pingxiang', '防城港': 'fangchenggang', '南通': 'nantong', '黔西南': 'qianxinan', '黄冈': 'huanggang',
             '台州': 'taizhou', '长沙': 'changsha', '常德': 'changde', '阜新': 'fuxin', '驻马店': 'zhumadian', '芜湖': 'wuhu',
             '中卫': 'zhongwei', '大理': 'dalishi', '舟山': 'zhoushan', '赤峰': 'chifeng', '滁州': 'chuzhou',
             '张家口': 'zhangjiakou', '镇江': 'zhenjiang', '东营': 'dongying', '双鸭山': 'shuangyashan', '绥化': 'suihua',
             '泰州': 'taizhou', '潮州': 'chaozhou', '毕节': 'bijieshi', '昆明': 'kunming', '嘉兴': 'jiaxing', '文山州': 'wenshan',
             '青岛': 'qingdao', '包头': 'baotou', '马鞍山': 'maanshan', '玉树': 'yushu', '海北': 'haibei', '迪庆': 'diqing',
             '西双版纳': 'xishuangbanna', '黄南': 'huangnan', '海西': 'haixi', '阿坝': 'aba', '怒江': 'nujiang', '德宏': 'dehong',
             '果洛': 'guoluo', '凉山': 'liangshan'}
add_city_dict = {
    # '白山': 'baishan', '大同': 'datong', '红河': 'honghe', '濮阳': 'puyang', '株洲': 'zhuzhou', '承德': 'chengde', '邢台': 'xingtai',
    # '和田': 'hetian', '长治': 'changzhi', '铁岭': 'tieling', '安阳': 'anyang', '九江': 'jiujiang', '吉安': 'jian', '南昌': 'nanchang',
    # '宜宾': 'yibin', '邵阳': 'shaoyang', '许昌': 'xuchang', '新乡': 'xinxiang', '那曲': 'naqu', '临夏': 'linxia', '衡阳': 'hengyang',
    # '邯郸': 'handan', '朝阳': 'chaoyang', '辽阳': 'liaoyang', '湘潭': 'xiangtan', '乌鲁木齐': 'wulumuqi', '岳阳': 'yueyang',
    # '通化': 'tonghua', '芜湖': 'wuhu'
    '抚州': 'jiangxifuzhou'
}
